import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import MarkScent from '@/components/mark-scent'
import RecommendationFeedback from '@/components/recommendation-feedback'
import SaveComparison from '@/components/save-comparison'

const labels:Record<string,string>={owned:'Own It',want:'Want to Try',tried:'Tried',favorite:'Favorites'}
const valid=new Set(Object.keys(labels))
export const metadata={title:'My Marks',robots:{index:false,follow:false}}

export default async function Collection({searchParams}:{searchParams:Promise<{status?:string}>}){
 const q=await searchParams,s=await createClient();let user:any=null
 try{const auth=await s.auth.getUser();user=auth.data.user}catch{}
 if(!user)redirect('/login?next=/collection')
 let rows:any[]=[],feedbackRows:any[]=[],recentRows:any[]=[],comparisonRows:any[]=[],historyRows:any[]=[],loadError=false
 try{const [result,feedback,recent,comparisons,history]=await Promise.all([s.from('collection_items').select('status,created_at,perfumes(id,name,slug,image_url,brands(name))').eq('user_id',user.id).order('created_at',{ascending:false}),s.from('recommendation_feedback').select('feedback,updated_at,perfumes(id,name,slug,brands(name))').eq('user_id',user.id).order('updated_at',{ascending:false}),s.from('recently_viewed_perfumes').select('viewed_at,perfumes(id,name,slug,image_url,brands(name))').eq('user_id',user.id).order('viewed_at',{ascending:false}).limit(8),s.from('saved_comparisons').select('created_at,perfume_a_id,perfume_b_id').eq('user_id',user.id).order('created_at',{ascending:false}).limit(12),s.from('recommendation_history').select('id,perfume_slug,loved_terms,avoided_terms,sweetness,projection,longevity,max_price,created_at').eq('user_id',user.id).order('created_at',{ascending:false}).limit(10)]);if(result.error)loadError=true;else rows=result.data||[];if(!feedback.error)feedbackRows=feedback.data||[];if(!recent.error)recentRows=recent.data||[];if(!comparisons.error&&comparisons.data?.length){const ids=[...new Set(comparisons.data.flatMap((x:any)=>[x.perfume_a_id,x.perfume_b_id]))];const ps=await s.from('perfumes').select('id,name,slug,brands(name)').in('id',ids).eq('status','published');const byId=new Map((ps.data||[]).map((p:any)=>[p.id,p]));comparisonRows=comparisons.data.map((x:any)=>({...x,a:byId.get(x.perfume_a_id),b:byId.get(x.perfume_b_id)})).filter((x:any)=>x.a&&x.b)};if(!history.error)historyRows=history.data||[]}catch{loadError=true}
 const grouped=new Map<string,{p:any,statuses:string[]}>()
 for(const row of rows){const p:any=row.perfumes;if(!p)continue;const old=grouped.get(p.id)||{p,statuses:[]};if(!old.statuses.includes(row.status))old.statuses.push(row.status);grouped.set(p.id,old)}
 const filter=q.status&&valid.has(q.status)?q.status:'',items=[...grouped.values()].filter(x=>!filter||x.statuses.includes(filter))
 const counts=Object.fromEntries(Object.keys(labels).map(k=>[k,rows.filter(x=>x.status===k).length]))
 return <main><section className="collection-page"><div className="section-head"><div><p className="eyebrow">MY MARKS</p><h1 className="page-title">My Collection</h1><p className="lede">Keep track of what you own, what you want, what you've tried, and your favorites.</p></div><Link className="button" href="/discover">+ Add Fragrance</Link></div>
 {loadError?<div className="empty-state"><h2>Your Marks couldn't be loaded.</h2><p>Please refresh in a moment.</p></div>:<>
 <nav className="collection-tabs" aria-label="Collection filters"><Link className={!filter?'active':''} href="/collection">All ({grouped.size})</Link>{Object.entries(labels).map(([k,v])=><Link className={filter===k?'active':''} href={'/collection?status='+k} key={k}>{v} ({counts[k]})</Link>)}</nav>
 {items.length?<div className="collection-grid">{items.map(({p,statuses})=><article className="collection-card" key={p.id}><div className="collection-bottle">{p.image_url?<img src={p.image_url} alt={p.name+" by "+(p.brands?.name||"Scentmarked")} loading="lazy"/>:<div className="catalog-placeholder"><small>{p.brands?.name||"Scentmarked"}</small><b>{p.name}</b></div>}</div><small>{p.brands?.name}</small><Link href={'/perfume/'+p.slug}><h3>{p.name}</h3></Link><p>{statuses.map(x=>labels[x]||x).join(' · ')}</p><MarkScent perfumeId={p.id} initial={statuses}/></article>)}</div>:<div className="empty-state"><h2>{filter?'No fragrances in '+labels[filter]+' yet.':'No Marks yet.'}</h2><p>Explore the catalog and mark scents as you discover them.</p><Link className="button" href="/discover">Discover fragrances</Link></div>}
 </>}
 <section className="collection-recent"><div className="section-head"><div><p className="eyebrow">RECENTLY VIEWED</p><h2>Pick up where you left off</h2><p>Your latest fragrance profile visits. This history is private to your account.</p></div></div>{recentRows.length?<div className="collection-grid">{recentRows.map((row:any)=>{const p=row.perfumes;return p?<article className="collection-card" key={p.id}><div className="collection-bottle">{p.image_url?<img src={p.image_url} alt={p.name+" by "+(p.brands?.name||"Scentmarked")} loading="lazy"/>:<div className="catalog-placeholder"><small>{p.brands?.name||"Scentmarked"}</small><b>{p.name}</b></div>}</div><small>{p.brands?.name}</small><Link href={'/perfume/'+p.slug}><h3>{p.name}</h3></Link><div className="result-actions"><Link className="text-link" href={'/perfume/'+p.slug}>View profile →</Link><Link className="text-link" href={'/matches?perfume='+p.slug}>Find similar →</Link></div></article>:null})}</div>:<div className="empty-state"><p>Your recently viewed fragrances will appear here after you open perfume profiles while signed in.</p><Link className="button" href="/discover">Discover fragrances</Link></div>}</section>
 <section className="collection-history"><div className="section-head"><div><p className="eyebrow">MATCH HISTORY</p><h2>Recent recommendation searches</h2><p>Revisit the criteria you used for previous ScentMarked recommendations.</p></div></div>{historyRows.length?<div className="collection-grid">{historyRows.map((row:any)=>{const qp=new URLSearchParams();if(row.perfume_slug)qp.set('perfume',row.perfume_slug);if(row.loved_terms?.length)qp.set('love',row.loved_terms.join(', '));if(row.avoided_terms?.length)qp.set('avoid',row.avoided_terms.join(', '));if(row.sweetness)qp.set('sweetness',String(row.sweetness));if(row.projection)qp.set('projection',String(row.projection));if(row.longevity)qp.set('longevity',String(row.longevity));if(row.max_price)qp.set('maxPrice',String(row.max_price));const summary=[row.perfume_slug?'Reference scent':'Preferences only',row.loved_terms?.length?'Love: '+row.loved_terms.join(', '):'',row.avoided_terms?.length?'Avoid: '+row.avoided_terms.join(', '):'',row.max_price?'Budget: $'+row.max_price:''].filter(Boolean);return <article className="collection-card" key={row.id}><small>{new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(new Date(row.created_at))}</small><h3>{row.perfume_slug?'Scent match search':'Preference match search'}</h3><p>{summary.join(' · ')}</p><Link className="button ghost" href={'/matches?'+qp.toString()}>Run Again →</Link></article>})}</div>:<div className="empty-state"><p>Your recommendation searches will appear here after you run Match while signed in.</p><Link className="button" href="/matches">Find Matches</Link></div>}</section>
 <section className="collection-comparisons"><div className="section-head"><div><p className="eyebrow">SAVED COMPARISONS</p><h2>Pairs you're considering</h2><p>Return to fragrance comparisons without searching for both scents again.</p></div></div>{comparisonRows.length?<div className="collection-grid">{comparisonRows.map((row:any)=><article className="collection-card" key={row.perfume_a_id+'-'+row.perfume_b_id}><small>{row.a.brands?.name||'Fragrance'} vs {row.b.brands?.name||'Fragrance'}</small><h3>{row.a.name} ⇄ {row.b.name}</h3><div className="result-actions"><Link className="text-link" href={'/compare?a='+row.a.slug+'&b='+row.b.slug}>Reopen comparison →</Link></div><SaveComparison aId={row.perfume_a_id} bId={row.perfume_b_id} initialSaved={true}/></article>)}</div>:<div className="empty-state"><p>You haven't saved any comparisons yet.</p><Link className="button" href="/compare">Compare fragrances</Link></div>}</section>
 <section className="collection-feedback"><div className="section-head"><div><p className="eyebrow">RECOMMENDATION FEEDBACK</p><h2>My Recommendation Preferences</h2><p>These choices make future Match results more personal. They adjust ordering by a small amount without changing a fragrance's core match percentage.</p></div></div>{feedbackRows.length?<div className="collection-grid">{feedbackRows.map((row:any)=>{const p=row.perfumes;return p?<article className="collection-card" key={p.id}><small>{p.brands?.name}</small><Link href={'/perfume/'+p.slug}><h3>{p.name}</h3></Link><RecommendationFeedback perfumeId={p.id} initialFeedback={row.feedback} label="Change this preference" refreshAfterChange/><Link className="text-link" href={'/matches?perfume='+p.slug}>Find matches →</Link></article>:null})}</div>:<div className="empty-state"><p>You haven't rated any recommendations yet. Use More Like This or Less Like This on Match results to teach ScentMarked your preferences.</p><Link className="button" href="/matches">Find Matches</Link></div>}</section>
 </section></main>
}