import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import PerfumeSearchPicker from '@/components/perfume-search-picker'

type P={id:string;name:string;slug:string;image_url?:string|null;brands:any;perfume_notes:any[];perfume_accords:any[]}
const noteNames=(p:P)=>(p?.perfume_notes||[]).map((x:any)=>x.notes?.name).filter(Boolean) as string[]
const positionWeight=(p?:string)=>p==='base'?1.25:p==='heart'?1.15:p==='top'?1.05:1
const noteMap=(p:P)=>{const m=new Map<string,{position:string;weight:number}>();for(const x of p?.perfume_notes||[]){const name=x.notes?.name;if(!name)continue;const w=positionWeight(x.position),old=m.get(name);if(!old||w>old.weight)m.set(name,{position:x.position||'unspecified',weight:w})}return m}
const accordRows=(p:P)=>(p?.perfume_accords||[]).filter((x:any)=>x.accords?.name&&Number(x.strength)>0)
function noteScore(a:P,b:P,f:Map<string,number>,total:number){const A=noteMap(a),B=noteMap(b),shared=[...A.keys()].filter(x=>B.has(x)),rarity=(n:string)=>Math.log(1+total/(f.get(n)||1)),sharedWeight=(n:string)=>{const x=A.get(n)!,y=B.get(n)!,positionBonus=x.position===y.position&&x.position!=='unspecified'?1.18:1;return rarity(n)*Math.min(x.weight,y.weight)*positionBonus},sw=shared.reduce((s,n)=>s+sharedWeight(n),0),union=[...new Set([...A.keys(),...B.keys()])],uw=union.reduce((s,n)=>s+rarity(n)*Math.max(A.get(n)?.weight||0,B.get(n)?.weight||0),0),similarity=uw?Math.min(100,sw/uw*100):0,coverage=Math.min(1,Math.min(A.size,B.size)/6),positionMatches=shared.filter(n=>A.get(n)?.position===B.get(n)?.position&&A.get(n)?.position!=='unspecified');return{value:similarity*(.72+.28*coverage),shared,positionMatches,coverage}}
function accordScore(a:P,b:P){const A=new Map(accordRows(a).map((x:any)=>[x.accords.name,Number(x.strength)])),B=new Map(accordRows(b).map((x:any)=>[x.accords.name,Number(x.strength)])),names=[...new Set([...A.keys(),...B.keys()])];if(!A.size||!B.size)return null;let diff=0;for(const n of names)diff+=Math.abs((A.get(n)||0)-(B.get(n)||0));const value=Math.max(0,100-diff/Math.max(1,names.length));return{value,shared:[...A.keys()].filter(n=>B.has(n))}}
function score(a:P,b:P,f:Map<string,number>,total:number){const n=noteScore(a,b,f,total),ac=accordScore(a,b);const value=ac?n.value*.65+ac.value*.35:n.value;const coverage=Math.min(1,(n.coverage+(ac?Math.min(1,Math.min(accordRows(a).length,accordRows(b).length)/4):0))/ (ac?2:1));return{score:Math.round(value),shared:n.shared,positionMatches:n.positionMatches,sharedAccords:ac?.shared||[],usesAccords:!!ac,confidence:coverage>=.85?'High':coverage>=.5?'Medium':'Limited'}}
export const metadata={title:'Find a Scent Match',description:'Compare verified fragrance notes and accords to discover scents with similar DNA.',alternates:{canonical:'/matches'},openGraph:{title:'Find a Scent Match | Scentmarked',description:'Compare verified fragrance notes and accords to discover scents with similar DNA.',url:'/matches',type:'website'}}

export default async function Matches({searchParams}:{searchParams:Promise<{perfume?:string;love?:string;avoid?:string}>}){
 const params=await searchParams,{perfume}=params,love=(params.love||'').split(',').map(x=>x.trim()).filter(Boolean),avoid=(params.avoid||'').split(',').map(x=>x.trim()).filter(Boolean),loveLower=love.map(x=>x.toLowerCase()),avoidLower=avoid.map(x=>x.toLowerCase());let perfumes:P[]=[],loadError=false
 try{const s=await createClient();const result=await s.from('perfumes').select('id,name,slug,image_url,brands(name),perfume_notes(position,notes(name)),perfume_accords(strength,source_type,accords(name))').eq('status','published').order('name');if(result.error)loadError=true;else perfumes=(result.data||[]) as unknown as P[]}catch{loadError=true}
 const eligible=perfumes.filter(p=>noteNames(p).length||accordRows(p).length),requested=perfume?eligible.find(p=>p.slug===perfume):undefined,invalidSelection=!!(perfume&&!requested),selected=invalidSelection?undefined:(requested||eligible[0]),freq=new Map<string,number>();eligible.forEach(p=>new Set(noteNames(p)).forEach(n=>freq.set(n,(freq.get(n)||0)+1)))
 const candidates=eligible.filter(p=>!selected||p.id!==selected.id).map(p=>{const base=selected?score(selected,p,freq,eligible.length):{score:0,shared:[],positionMatches:[],sharedAccords:[],usesAccords:false,confidence:'Limited'},notes=noteNames(p),lower=notes.map(n=>n.toLowerCase()),loved=love.filter((_,i)=>lower.some(n=>n.includes(loveLower[i]))),avoided=avoid.filter((_,i)=>lower.some(n=>n.includes(avoidLower[i]))),preferenceScore=love.length?Math.round(loved.length/love.length*100):0,combined=selected&&love.length?Math.round(base.score*.55+preferenceScore*.45):love.length?preferenceScore:base.score;return{...p,...base,score:combined,loved,avoided,preferenceScore}}).filter((p:any)=>!p.avoided.length);const matches=candidates.sort((a:any,b:any)=>b.score-a.score||b.loved.length-a.loved.length).slice(0,12),hasPreferences=love.length>0||avoid.length>0;
 return <main><section className="match-page"><div className="match-banner"><div><p className="eyebrow">SCENTMARKED MATCH</p><h1>Find Your Scent Match</h1><p>Tell us what you love. Start with a favorite fragrance, preferred notes, or both, and ScentMarked will rank matches using verified catalog data.</p><form action="/matches" className="preference-match-form"><PerfumeSearchPicker name="perfume" label="A fragrance you love (optional)" selectedSlug={selected?.slug} options={eligible.map(p=>({id:p.id,name:p.name,slug:p.slug,brand:p.brands?.name||'Scentmarked'}))}/><div className="preference-fields"><label>Notes you love<input name="love" defaultValue={params.love||''} placeholder="Vanilla, marshmallow, strawberry"/></label><label>Notes to avoid<input name="avoid" defaultValue={params.avoid||''} placeholder="Leather, patchouli, oud"/></label></div><small>Separate multiple notes with commas. ScentMarked matches these against verified note data.</small><button className="button">Find My Matches</button></form><div className="popular"><b>Popular searches</b>{eligible.slice(0,6).map(p=><Link key={p.id} href={'/matches?perfume='+p.slug}>{p.name}</Link>)}</div></div><div className="match-art"><div className="match-bottle">S</div><i>Different paths.<br/>Same beautiful<br/>destination.</i></div></div>
 {hasPreferences&&<div className="preference-summary"><b>Your preferences</b>{love.length>0&&<span>Love: {love.join(' · ')}</span>}{avoid.length>0&&<span>Avoid: {avoid.join(' · ')}</span>}</div>}
 {loadError?<div className="empty-state"><h2>Matches are temporarily unavailable.</h2><p>Please refresh in a moment.</p></div>:invalidSelection?<div className="empty-state"><h2>That fragrance link is no longer available.</h2><p>The requested fragrance could not be found in the published catalog.</p><Link className="button" href="/matches">Start a new match</Link></div>:selected?<><div className="selected-scent"><div className="selected-bottle">{selected.image_url?<img src={selected.image_url} alt={selected.name+" by "+(selected.brands?.name||"Scentmarked")}/>:<div className="catalog-placeholder"><small>{selected.brands?.name||"Scentmarked"}</small><b>{selected.name}</b></div>}</div><div><small>MATCHING AGAINST</small><h2>{selected.brands?.name} {selected.name}</h2><p>{noteNames(selected).join(' · ')}</p></div></div><div className="match-results">{matches.map((m:any)=><article key={m.id}><Link className="result-bottle product-profile-link" href={"/perfume/"+m.slug}>{m.image_url?<img src={m.image_url} alt={m.name+" by "+(m.brands?.name||"Scentmarked")} loading="lazy"/>:<div className="catalog-placeholder"><small>{m.brands?.name||"Scentmarked"}</small><b>{m.name}</b></div>}</Link><small>{m.brands?.name}</small><h3><Link className="card-title-link" href={"/perfume/"+m.slug}>{m.name}</Link></h3><div className="result-score"><strong>{m.score}%</strong><span>{m.usesAccords?'note + accord similarity':'note similarity'}</span></div>{m.loved.length>0&&<p className="preference-reason"><b>Matches your taste:</b> {m.loved.join(', ')}</p>}<p>{selected?(m.shared.length?'Shared with '+selected.name+': '+m.shared.slice(0,5).join(', '):'No exact notes shared with '+selected.name+'.'):'Recommended from your preferred notes.'}</p>{m.positionMatches.length>0&&<p>Same note position: {m.positionMatches.slice(0,4).join(', ')}</p>}{m.sharedAccords.length>0&&<p>Shared accords: {m.sharedAccords.slice(0,4).join(', ')}</p>}<small className="confidence">Data confidence: {m.confidence}</small><div className="result-actions"><Link href={'/perfume/'+m.slug}>View Scent</Link><Link href={'/compare?a='+selected.slug+'&b='+m.slug}>Compare</Link></div></article>)}</div><p className="match-disclaimer">Recommendations use verified catalog note data. Preferred notes raise a fragrance's match score and fragrances containing an entered avoid-note are excluded. When a favorite perfume is also selected, its note/accord similarity contributes to the ranking. These recommendations are not clone claims or guarantees that fragrances smell identical.</p></>:<div className="empty-state"><h2>No verified matches yet.</h2><p>More fragrances will appear here as note and accord data is verified.</p></div>}</section></main>
}
