-- ScentMarked production recovery baseline: core public schema
-- Reconstructed from verified production metadata on 2026-10-03.
-- Intended for a FRESH Supabase project. Do not apply to the existing production database.
-- RLS/policies, indexes, functions/triggers, grants, and storage are separate baseline layers.

create table public.brands (
  id uuid not null default gen_random_uuid(),
  name text not null,
  slug text not null,
  country text,
  website text,
  description text,
  logo_url text,
  created_at timestamptz default now(),
  banner_url text,
  instagram_url text,
  facebook_url text,
  tiktok_url text,
  constraint brands_pkey primary key (id),
  constraint brands_name_key unique (name),
  constraint brands_slug_key unique (slug)
);

create table public.accords (
  id uuid not null default gen_random_uuid(),
  name text not null,
  slug text not null,
  constraint accords_pkey primary key (id),
  constraint accords_name_key unique (name),
  constraint accords_slug_key unique (slug)
);

create table public.notes (
  id uuid not null default gen_random_uuid(),
  name text not null,
  slug text not null,
  category text,
  description text,
  image_url text,
  constraint notes_pkey primary key (id),
  constraint notes_name_key unique (name),
  constraint notes_slug_key unique (slug)
);

create table public.perfumes (
  id uuid not null default gen_random_uuid(),
  brand_id uuid,
  name text not null,
  slug text not null,
  release_year integer,
  concentration text,
  gender_marketing text,
  description text,
  image_url text,
  country text,
  price_low numeric,
  price_high numeric,
  status text not null default 'draft',
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint perfumes_pkey primary key (id),
  constraint perfumes_slug_key unique (slug),
  constraint perfumes_status_check check (status = any (array['draft'::text,'published'::text])),
  constraint perfumes_brand_id_fkey foreign key (brand_id) references public.brands(id) on delete set null
);

create table public.profiles (
  id uuid not null,
  display_name text,
  avatar_url text,
  is_admin boolean not null default false,
  created_at timestamptz default now(),
  scent_loved_notes text[] not null default '{}'::text[],
  scent_avoided_notes text[] not null default '{}'::text[],
  scent_sweetness smallint,
  scent_projection smallint,
  scent_longevity smallint,
  scent_max_price numeric,
  scent_occasions text[] default '{}'::text[],
  scent_vibes text[] default '{}'::text[],
  scent_presentations text[] default '{}'::text[],
  scent_profile_completed_at timestamptz,
  scent_favorite_perfume_ids uuid[] default '{}'::uuid[],
  constraint profiles_pkey primary key (id),
  constraint profiles_id_fkey foreign key (id) references auth.users(id) on delete cascade,
  constraint profiles_scent_sweetness_check check (scent_sweetness is null or scent_sweetness between 1 and 5),
  constraint profiles_scent_projection_check check (scent_projection is null or scent_projection between 1 and 5),
  constraint profiles_scent_longevity_check check (scent_longevity is null or scent_longevity between 1 and 5),
  constraint profiles_scent_max_price_check check (scent_max_price is null or scent_max_price >= 0)
);

create table public.perfume_notes (
  perfume_id uuid not null,
  note_id uuid not null,
  "position" text not null default 'unspecified',
  constraint perfume_notes_pkey primary key (perfume_id,note_id,"position"),
  constraint perfume_notes_position_check check ("position" = any (array['top'::text,'heart'::text,'base'::text,'unspecified'::text])),
  constraint perfume_notes_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade,
  constraint perfume_notes_note_id_fkey foreign key (note_id) references public.notes(id) on delete cascade
);

create table public.perfume_accords (
  perfume_id uuid not null,
  accord_id uuid not null,
  strength integer,
  source_type text not null default 'editorial',
  constraint perfume_accords_pkey primary key (perfume_id,accord_id,source_type),
  constraint perfume_accords_source_type_check check (source_type = any (array['editorial'::text,'manufacturer'::text,'community'::text])),
  constraint perfume_accords_strength_check check (strength >= 0 and strength <= 100),
  constraint perfume_accords_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade,
  constraint perfume_accords_accord_id_fkey foreign key (accord_id) references public.accords(id) on delete cascade
);

create table public.perfume_sources (
  id bigint generated by default as identity not null,
  perfume_id uuid not null,
  source_name text not null,
  source_url text not null,
  source_type text not null default 'retailer_reference',
  fields_verified text[] not null default '{}'::text[],
  checked_at timestamptz not null default now(),
  is_primary boolean not null default false,
  constraint perfume_sources_pkey primary key (id),
  constraint perfume_sources_perfume_id_source_url_key unique (perfume_id,source_url),
  constraint perfume_sources_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.perfume_image_provenance (
  perfume_id uuid not null,
  source_name text not null,
  source_url text,
  rights_basis text not null,
  rights_note text,
  asset_url text not null,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfume_image_provenance_pkey primary key (perfume_id),
  constraint perfume_image_provenance_rights_basis_check check (rights_basis = any (array['user_owned'::text,'licensed'::text,'brand_media_permission'::text,'supplier_permission'::text,'other_documented_permission'::text])),
  constraint perfume_image_provenance_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.scent_relationships (
  id uuid not null default gen_random_uuid(),
  source_perfume_id uuid,
  target_perfume_id uuid,
  relationship_type text not null,
  confidence numeric,
  evidence_source text,
  created_at timestamptz default now(),
  constraint scent_relationships_pkey primary key (id),
  constraint scent_relationships_source_perfume_id_target_perfume_id_rel_key unique (source_perfume_id,target_perfume_id,relationship_type),
  constraint scent_relationships_confidence_check check (confidence >= 0 and confidence <= 100),
  constraint scent_relationships_relationship_type_check check (relationship_type = any (array['manufacturer_inspired_by'::text,'community_comparison'::text,'similar_dna'::text,'possible_clone'::text,'flanker'::text])),
  constraint scent_relationships_source_perfume_id_fkey foreign key (source_perfume_id) references public.perfumes(id) on delete cascade,
  constraint scent_relationships_target_perfume_id_fkey foreign key (target_perfume_id) references public.perfumes(id) on delete cascade
);

create table public.collection_items (
  user_id uuid not null,
  perfume_id uuid not null,
  status text not null,
  created_at timestamptz default now(),
  constraint collection_items_pkey primary key (user_id,perfume_id,status),
  constraint collection_items_status_check check (status = any (array['owned'::text,'want'::text,'tried'::text,'favorite'::text])),
  constraint collection_items_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint collection_items_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint collection_items_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.ratings (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  perfume_id uuid,
  overall integer,
  longevity integer,
  projection integer,
  sweetness integer,
  review text,
  created_at timestamptz default now(),
  constraint ratings_pkey primary key (id),
  constraint ratings_user_id_perfume_id_key unique (user_id,perfume_id),
  constraint ratings_overall_check check (overall >= 1 and overall <= 5),
  constraint ratings_longevity_check check (longevity >= 1 and longevity <= 5),
  constraint ratings_projection_check check (projection >= 1 and projection <= 5),
  constraint ratings_sweetness_check check (sweetness >= 1 and sweetness <= 5),
  constraint ratings_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint ratings_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint ratings_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.comparison_votes (
  id uuid not null default gen_random_uuid(),
  user_id uuid,
  perfume_a_id uuid,
  perfume_b_id uuid,
  similarity integer,
  sweeter uuid,
  stronger uuid,
  longer uuid,
  more_gourmand uuid,
  created_at timestamptz default now(),
  constraint comparison_votes_pkey primary key (id),
  constraint comparison_votes_user_id_perfume_a_id_perfume_b_id_key unique (user_id,perfume_a_id,perfume_b_id),
  constraint comparison_votes_similarity_check check (similarity >= 1 and similarity <= 5),
  constraint comparison_votes_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint comparison_votes_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete set null,
  constraint comparison_votes_perfume_a_id_fkey foreign key (perfume_a_id) references public.perfumes(id) on delete cascade,
  constraint comparison_votes_perfume_b_id_fkey foreign key (perfume_b_id) references public.perfumes(id) on delete cascade,
  constraint comparison_votes_sweeter_fkey foreign key (sweeter) references public.perfumes(id),
  constraint comparison_votes_stronger_fkey foreign key (stronger) references public.perfumes(id),
  constraint comparison_votes_longer_fkey foreign key (longer) references public.perfumes(id),
  constraint comparison_votes_more_gourmand_fkey foreign key (more_gourmand) references public.perfumes(id)
);

create table public.recently_viewed_perfumes (
  user_id uuid not null,
  perfume_id uuid not null,
  viewed_at timestamptz not null default now(),
  constraint recently_viewed_perfumes_pkey primary key (user_id,perfume_id),
  constraint recently_viewed_perfumes_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint recently_viewed_perfumes_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint recently_viewed_perfumes_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.recommendation_feedback (
  user_id uuid not null,
  perfume_id uuid not null,
  feedback text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint recommendation_feedback_pkey primary key (user_id,perfume_id),
  constraint recommendation_feedback_feedback_check check (feedback = any (array['more_like_this'::text,'less_like_this'::text])),
  constraint recommendation_feedback_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint recommendation_feedback_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint recommendation_feedback_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.recommendation_history (
  id bigint generated always as identity not null,
  user_id uuid not null,
  perfume_id uuid,
  perfume_slug text,
  loved_terms text[] not null default '{}'::text[],
  avoided_terms text[] not null default '{}'::text[],
  sweetness smallint,
  projection smallint,
  longevity smallint,
  max_price numeric,
  result_perfume_ids uuid[] not null default '{}'::uuid[],
  created_at timestamptz not null default now(),
  criteria_key text not null,
  constraint recommendation_history_pkey primary key (id),
  constraint recommendation_history_user_criteria_key unique (user_id,criteria_key),
  constraint recommendation_history_sweetness_check check (sweetness >= 1 and sweetness <= 5),
  constraint recommendation_history_projection_check check (projection >= 1 and projection <= 5),
  constraint recommendation_history_longevity_check check (longevity >= 1 and longevity <= 5),
  constraint recommendation_history_max_price_check check (max_price is null or max_price >= 0),
  constraint recommendation_history_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint recommendation_history_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint recommendation_history_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete set null
);

create table public.saved_comparisons (
  user_id uuid not null,
  perfume_a_id uuid not null,
  perfume_b_id uuid not null,
  created_at timestamptz not null default now(),
  constraint saved_comparisons_pkey primary key (user_id,perfume_a_id,perfume_b_id),
  constraint saved_comparisons_check check (perfume_a_id <> perfume_b_id),
  constraint saved_comparisons_canonical_pair check (perfume_a_id::text < perfume_b_id::text),
  constraint saved_comparisons_user_id_fkey foreign key (user_id) references auth.users(id) on delete cascade,
  constraint saved_comparisons_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete cascade,
  constraint saved_comparisons_perfume_a_id_fkey foreign key (perfume_a_id) references public.perfumes(id) on delete cascade,
  constraint saved_comparisons_perfume_b_id_fkey foreign key (perfume_b_id) references public.perfumes(id) on delete cascade
);

create table public.perfume_affiliate_offers (
  id bigint generated by default as identity not null,
  perfume_id uuid not null,
  merchant_name text not null,
  affiliate_url text not null,
  price numeric,
  currency text not null default 'USD',
  label text,
  is_active boolean not null default true,
  priority integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint perfume_affiliate_offers_pkey primary key (id),
  constraint perfume_affiliate_offers_price_check check (price is null or price >= 0),
  constraint perfume_affiliate_offers_url_check check (affiliate_url ~ '^https?://'::text),
  constraint perfume_affiliate_offers_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.affiliate_clicks (
  id bigint generated by default as identity not null,
  offer_id bigint not null,
  perfume_id uuid not null,
  placement text not null default 'profile',
  clicked_at timestamptz not null default now(),
  constraint affiliate_clicks_pkey primary key (id),
  constraint affiliate_clicks_offer_id_fkey foreign key (offer_id) references public.perfume_affiliate_offers(id) on delete cascade,
  constraint affiliate_clicks_perfume_id_fkey foreign key (perfume_id) references public.perfumes(id) on delete cascade
);

create table public.contact_messages (
  id bigint generated by default as identity not null,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  category text not null default 'general',
  subject text not null,
  message text not null,
  status text not null default 'new',
  user_id uuid,
  constraint contact_messages_pkey primary key (id),
  constraint contact_messages_category_check check (category = any (array['general'::text,'catalog'::text,'missing_fragrance'::text,'community'::text,'privacy'::text,'rights'::text])),
  constraint contact_messages_email_check check (char_length(email) >= 3 and char_length(email) <= 254),
  constraint contact_messages_message_check check (char_length(message) >= 1 and char_length(message) <= 4000),
  constraint contact_messages_name_check check (char_length(name) >= 1 and char_length(name) <= 100),
  constraint contact_messages_status_check check (status = any (array['new'::text,'reviewing'::text,'resolved'::text])),
  constraint contact_messages_subject_check check (char_length(subject) >= 1 and char_length(subject) <= 160),
  constraint contact_messages_user_id_fkey foreign key (user_id) references auth.users(id) on delete set null,
  constraint contact_messages_user_profile_fkey foreign key (user_id) references public.profiles(id) on delete set null
);

create table public.site_content (
  id bigint generated by default as identity not null,
  content_key text not null,
  content_type text not null default 'section',
  title text,
  subtitle text,
  body text,
  image_url text,
  mobile_image_url text,
  alt_text text,
  cta_label text,
  cta_url text,
  placement text,
  sort_order integer not null default 100,
  is_active boolean not null default true,
  starts_at timestamptz,
  ends_at timestamptz,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint site_content_pkey primary key (id),
  constraint site_content_content_key_key unique (content_key),
  constraint site_content_content_type_check check (content_type = any (array['section'::text,'banner'::text,'background'::text,'hero'::text,'global'::text]))
);
