export type MatchPerfume={id:string;name:string;slug:string;image_url?:string|null;price_low?:number|null;price_high?:number|null;brands:any;perfume_notes:any[];perfume_accords:any[];ratings?:any[]}

export const noteNames=(p:MatchPerfume)=>(p?.perfume_notes||[]).map((x:any)=>x.notes?.name).filter(Boolean) as string[]
const positionWeight=(p?:string)=>p==='base'?1.25:p==='heart'?1.15:p==='top'?1.05:1
const noteMap=(p:MatchPerfume)=>{const m=new Map<string,{position:string;weight:number}>();for(const x of p?.perfume_notes||[]){const name=x.notes?.name;if(!name)continue;const w=positionWeight(x.position),old=m.get(name);if(!old||w>old.weight)m.set(name,{position:x.position||'unspecified',weight:w})}return m}
export const accordRows=(p:MatchPerfume)=>(p?.perfume_accords||[]).filter((x:any)=>x.accords?.name&&Number(x.strength)>0)
export const preferenceTerms=(p:MatchPerfume)=>{const notes=noteNames(p).map(name=>({name,kind:'note',strength:100})),accords=accordRows(p).map((x:any)=>({name:String(x.accords.name),kind:'accord',strength:Number(x.strength)||0}));return [...notes,...accords]}

function noteScore(a:MatchPerfume,b:MatchPerfume,f:Map<string,number>,total:number){const A=noteMap(a),B=noteMap(b),shared=[...A.keys()].filter(x=>B.has(x)),rarity=(n:string)=>Math.log(1+total/(f.get(n)||1)),sharedWeight=(n:string)=>{const x=A.get(n)!,y=B.get(n)!,positionBonus=x.position===y.position&&x.position!=='unspecified'?1.18:1;return rarity(n)*Math.min(x.weight,y.weight)*positionBonus},sw=shared.reduce((s,n)=>s+sharedWeight(n),0),union=[...new Set([...A.keys(),...B.keys()])],uw=union.reduce((s,n)=>s+rarity(n)*Math.max(A.get(n)?.weight||0,B.get(n)?.weight||0),0),similarity=uw?Math.min(100,sw/uw*100):0,coverage=Math.min(1,Math.min(A.size,B.size)/6),positionMatches=shared.filter(n=>A.get(n)?.position===B.get(n)?.position&&A.get(n)?.position!=='unspecified');return{value:similarity*(.72+.28*coverage),shared,positionMatches,coverage}}
function accordScore(a:MatchPerfume,b:MatchPerfume){const A=new Map(accordRows(a).map((x:any)=>[x.accords.name,Number(x.strength)])),B=new Map(accordRows(b).map((x:any)=>[x.accords.name,Number(x.strength)])),names=[...new Set([...A.keys(),...B.keys()])];if(!A.size||!B.size)return null;let diff=0;for(const n of names)diff+=Math.abs((A.get(n)||0)-(B.get(n)||0));const value=Math.max(0,100-diff/Math.max(1,names.length));return{value,shared:[...A.keys()].filter(n=>B.has(n))}}

export function scentSimilarityScore(a:MatchPerfume,b:MatchPerfume,f:Map<string,number>,total:number){const n=noteScore(a,b,f,total),ac=accordScore(a,b);const value=ac?n.value*.65+ac.value*.35:n.value;const coverage=Math.min(1,(n.coverage+(ac?Math.min(1,Math.min(accordRows(a).length,accordRows(b).length)/4):0))/(ac?2:1));return{score:Math.round(value),shared:n.shared,positionMatches:n.positionMatches,sharedAccords:ac?.shared||[],usesAccords:!!ac,confidence:coverage>=.85?'High':coverage>=.5?'Medium':'Limited'}}
