import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export const metadata={title:'Catalog Studio',robots:{index:false,follow:false}}
export default async function Admin({searchParams}:{searchParams:Promise<{q?:string;status?:string;needs?:string}>}){
 const q=await searchParams,s=await createClient();let user:any=null
 try{const auth=await s.auth.getUser();user=auth.data.user}catch{}
 if(!user)redirect('/login?next=/admin')
 let isAdmin=false;try{const result=await s.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();isAdmin=result.data?.is_admin===true}catch{}
 if(!isAdmin)redirect('/discover')
 let perfumes:any[]=[],loadError=false
 try{const r=await s.from('perfumes').select('id,name,slug,status,updated_at,brands(name),perfume_notes(note_id),perfume_sources(id),perfume_accords(accord_id),image_url,perfume_image_provenance(perfume_id)').order('updated_at',{ascending:false}).limit(500);if(r.error)loadError=true;else perfumes=r.data||[]}catch{loadError=true}
 const search=(q.q||'').trim().toLowerCase(),status=q.status||'',needs=q.needs||''
 const missing=(p:any)=>({notes:!(p.perfume_notes||[]).length,sources:!(p.perfume_sources||[]).length,accords:!(p.perfume_accords||[]).length,image:!p.image_url,imageRights:!((p.perfume_image_provenance||[]).length)})
 const data=perfumes.filter((p:any)=>{const m=missing(p);return(!search||(`${p.name} ${p.brands?.name||''}`).toLowerCase().includes(search))&&(!status||p.status===status)&&(!needs||(needs==='notes'&&m.notes)||(needs==='sources'&&m.sources)||(needs==='accords'&&m.accords)||(needs==='image'&&m.image)||(needs==='image-rights'&&!m.image&&m.imageRights)||(needs==='enrichment'&&(m.notes||m.sources)))})
 const incomplete=perfumes.filter((p:any)=>{const m=missing(p);return m.notes||m.sources}).length
 return <main><section className="admin-catalog"><p className="eyebrow">SCENTMARKED STUDIO</p><div className="admin-heading"><div><h1 className="page-title">Catalog Studio</h1><p>Manage fragrance records, verification and publishing.</p></div><Link className="button" href="/admin/perfumes/new">Add Fragrance</Link></div>
 <div className="admin-stats"><span><b>{perfumes.length}</b>Catalog records</span><span><b>{perfumes.filter((p:any)=>p.status==='published').length}</b>Published</span><span><b>{perfumes.filter((p:any)=>p.status==='draft').length}</b>Drafts</span><span><b>{incomplete}</b>Need enrichment</span><span><b>{perfumes.filter((p:any)=>!p.image_url).length}</b>Need images</span><span><b>{perfumes.filter((p:any)=>p.image_url&&(p.perfume_image_provenance||[]).length).length}</b>Rights verified</span></div>
 <form action="/admin" className="admin-filters"><input name="q" defaultValue={q.q||''} placeholder="Search fragrance or brand…"/><select name="status" defaultValue={status}><option value="">All statuses</option><option value="published">Published</option><option value="draft">Draft</option></select><select name="needs" defaultValue={needs}><option value="">All data states</option><option value="enrichment">Needs enrichment</option><option value="notes">Missing notes</option><option value="accords">Missing accords</option><option value="sources">Missing source</option><option value="image">Missing image</option><option value="image-rights">Image missing rights</option></select><button className="button">Filter</button>{(search||status||needs)&&<Link href="/admin">Clear</Link>}</form>
 {loadError?<div className="empty-state"><h2>Catalog records could not be loaded.</h2></div>:<><p className="muted">{data.length} record{data.length===1?'':'s'} shown</p><div className="admin-list">{data.length?data.map((p:any)=>{const notes=(p.perfume_notes||[]).length,sources=(p.perfume_sources||[]).length,accords=(p.perfume_accords||[]).length,hasImage=!!p.image_url,hasImageRights=(p.perfume_image_provenance||[]).length>0,ready=notes>0&&sources>0,missingParts=[!notes?'notes':'',!sources?'source':''].filter(Boolean);return <article key={p.id}><div><small>{p.brands?.name||'Brand'}</small><h2>{p.name}</h2><div className="admin-record-meta"><span className={'status-pill '+p.status}>{p.status}</span><span className={ready?'data-ready':'data-missing'}>{ready?'✓ Enriched':`Needs ${missingParts.join(' + ')}`}</span><span className={hasImage&&hasImageRights?'data-ready':'data-missing'}>{hasImage?(hasImageRights?'✓ Image rights':'Image missing rights'):'Needs image'}</span></div></div><div><Link className="button ghost" href={'/perfume/'+p.slug}>View</Link><Link className="button" href={'/admin/perfumes/'+p.id+'/edit'}>Edit</Link></div></article>}):<div className="empty-state"><h2>No records match those filters.</h2><Link href="/admin">Clear filters →</Link></div>}</div></>}</section></main>
}
