import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createServiceClient } from '@/lib/supabase/service'
import { affiliateMetrics, money, monetizationSummary } from '@/lib/monetization'
import { affiliateImportQuality } from '@/lib/affiliate-import'
import { affiliateReconciliationSummary } from '@/lib/affiliate-reconciliation'
import { subscriptionMetrics } from '@/lib/subscription-metrics'
import { revenueTrendMetrics } from '@/lib/revenue-trends'
import { rankAffiliateRevenue } from '@/lib/revenue-breakdowns'
import { filterRevenuePeriod, normalizeRevenuePeriod } from '@/lib/revenue-period'
import { revenueGoalMetrics } from '@/lib/revenue-goals'
import { revenueStreamForecast } from '@/lib/revenue-stream-forecast'
import { monetizationHealthAlerts } from '@/lib/monetization-health'
import { monthlyRevenueHistory } from '@/lib/revenue-history'
import { profitabilityMetrics } from '@/lib/profitability'
import { monthlyProfitHistory } from '@/lib/profit-history'
import { pnlSummary } from '@/lib/pnl-summary'
import { financialDateRange } from '@/lib/financial-export'
import { createSponsorship, recordRevenue, updateSponsorshipStatus, updateMembershipPlan, grantMembership, endManualMembership, importAffiliateCommissions, updateRevenueGoal, recordExpense, updateExpense, deleteExpense } from './actions'

export const metadata={title:'Monetization | ScentMarked Studio',robots:{index:false,follow:false}}

export default async function MonetizationPage({searchParams}:{searchParams:Promise<{error?:string;message?:string;period?:string}>}){
 const params=await searchParams
 const period=normalizeRevenuePeriod(params.period)
 const s=await createClient()
 const {data:{user}}=await s.auth.getUser()
 if(!user)redirect('/login?next=/admin/monetization')
 const {data:profile}=await s.from('profiles').select('is_admin').eq('id',user.id).maybeSingle()
 if(profile?.is_admin!==true)redirect('/discover')

 let transactions:any[]=[],campaigns:any[]=[],sponsorEvents:any[]=[],plans:any[]=[],subscriptions:any[]=[],affiliateClicks:any[]=[],affiliateOffers:any[]=[],perfumes:any[]=[],goalHistory:any[]=[],expenses:any[]=[],goalSettings:any=null,clickCount=0,configured=true
 try{
  const service=createServiceClient()
  const [tx,sp,events,planRows,subscriptionRows,clicks,clickRows,offerRows,perfumeRows,settingsRow,goalHistoryRows,expenseRows]=await Promise.all([
   service.from('monetization_transactions').select('revenue_type,gross_cents,fee_cents,status,occurred_at,currency,source_name,external_id,affiliate_offer_id,affiliate_click_id,affiliate_merchant,affiliate_placement,perfume_id').order('occurred_at',{ascending:false}).limit(5000),
   service.from('sponsorship_campaigns').select('id,name,sponsor_name,placement,status,starts_at,ends_at,budget_cents,currency').order('created_at',{ascending:false}).limit(100),
   service.from('sponsorship_events').select('campaign_id,event_type,placement,occurred_at').order('occurred_at',{ascending:false}).limit(10000),
   service.from('membership_plans').select('id,slug,name,description,price_cents,billing_interval,currency,entitlements,is_active,sort_order').order('sort_order'),
   service.from('member_subscriptions').select('id,user_id,plan_id,provider,status,current_period_end,cancel_at_period_end').in('status',['trialing','active','past_due']).limit(5000),
   service.from('affiliate_clicks').select('*',{count:'exact',head:true}),
   service.from('affiliate_clicks').select('id,offer_id,perfume_id,placement').limit(10000),
   service.from('perfume_affiliate_offers').select('id,perfume_id,merchant_name').limit(10000),
   service.from('perfumes').select('id,name').limit(10000),
   service.from('monetization_settings').select('monthly_revenue_goal_cents,currency').eq('id','default').maybeSingle(),
   service.from('monetization_goal_history').select('month_start,goal_cents,currency').order('month_start',{ascending:false}).limit(24),
   service.from('monetization_expenses').select('id,category,vendor,description,amount_cents,currency,incurred_at').order('incurred_at',{ascending:false}).limit(5000)
  ])
  if(!tx.error)transactions=tx.data||[]
  if(!sp.error)campaigns=sp.data||[]
  if(!events.error)sponsorEvents=events.data||[]
  if(!planRows.error)plans=planRows.data||[]
  if(!subscriptionRows.error)subscriptions=subscriptionRows.data||[]
  clickCount=clicks.count||0
  if(!clickRows.error)affiliateClicks=clickRows.data||[]
  if(!offerRows.error)affiliateOffers=offerRows.data||[]
  if(!perfumeRows.error)perfumes=perfumeRows.data||[]
  if(!settingsRow.error)goalSettings=settingsRow.data
  if(!goalHistoryRows.error)goalHistory=goalHistoryRows.data||[]
  if(!expenseRows.error)expenses=expenseRows.data||[]
 }catch{configured=false}

 const summary=monetizationSummary(transactions)
 const trends=revenueTrendMetrics(transactions)
 const goal=revenueGoalMetrics(trends.currentNetCents,Number(goalSettings?.monthly_revenue_goal_cents||100000))
 const streamForecast=revenueStreamForecast(transactions)
 const history=monthlyRevenueHistory(transactions,goalHistory,12)
 const profitability=profitabilityMetrics(trends.currentNetCents,expenses)
 const profitHistory=monthlyProfitHistory(transactions,expenses,12)
 const reportPnl=pnlSummary(transactions,expenses,reportRange.from,reportRange.to)
 const periodTransactions=filterRevenuePeriod(transactions,period)
 const topSources=rankAffiliateRevenue(periodTransactions,'source_name'),topMerchants=rankAffiliateRevenue(periodTransactions,'affiliate_merchant'),topPlacements=rankAffiliateRevenue(periodTransactions,'affiliate_placement'),topPerfumes=rankAffiliateRevenue(periodTransactions,'perfume_id')
 const perfumeNames=new Map(perfumes.map((x:any)=>[String(x.id),x.name]))
 const affiliate=affiliateMetrics(clickCount,transactions)
 const affiliateRows=transactions.filter((x:any)=>x.revenue_type==='affiliate'&&!['refunded','void'].includes(x.status)),affiliateQuality=affiliateImportQuality(affiliateRows)
 const reconciliation=affiliateReconciliationSummary(affiliateRows,affiliateClicks,affiliateOffers)
 const types=['affiliate','sponsorship','advertising','subscription'] as const
 const activeCampaigns=campaigns.filter((x:any)=>x.status==='active'||x.status==='scheduled')
 const membershipStats=subscriptionMetrics(subscriptions),premiumMembers=membershipStats.active
 const sponsorImpressions=sponsorEvents.filter((x:any)=>x.event_type==='impression').length,sponsorClicks=sponsorEvents.filter((x:any)=>x.event_type==='click').length,sponsorCtr=sponsorImpressions?sponsorClicks/sponsorImpressions:0
 const healthAlerts=monetizationHealthAlerts({goal,pendingCents:trends.pendingCents,realizedCents:trends.realizedCents,reconciliation,affiliateClicks:clickCount,affiliateConversions:affiliateRows.length,streams:streamForecast})

 return <main><section className="admin-catalog">
  <p className="eyebrow">SCENTMARKED STUDIO</p>
  <div className="admin-heading"><div><h1 className="page-title">Monetization</h1><p>Revenue infrastructure across affiliate commerce, sponsorships, advertising and future premium memberships.</p></div><div><Link className="button ghost" href="/admin/affiliates">Affiliate Analytics</Link><Link className="button ghost" href="/admin">Studio</Link></div></div>
  {params.error&&<p className="form-error" role="alert">{params.error}</p>}{params.message&&<p className="form-success" role="status">{params.message}</p>}
  <div className="admin-card"><div className="admin-heading"><div><h2>Monetization health</h2><p className="muted">Automatic checks highlight issues that may need attention.</p></div>{(reconciliation.conflict>0||reconciliation.unresolved>0)&&<Link className="button ghost" href="/admin/monetization/review">Review attribution</Link>}</div>{healthAlerts.length?<div className="admin-list">{healthAlerts.map(alert=><article key={alert.code}><div><small>{alert.severity.toUpperCase()}</small><h3>{alert.title}</h3><p className="muted">{alert.detail}</p></div></article>)}</div>:<p className="form-success">No monetization health alerts right now.</p>}</div>
  <div className="admin-card"><h2>Import affiliate commissions</h2><p className="muted">Upload a CSV from an affiliate network. Required columns: <code>external_id</code>, <code>gross</code>, <code>occurred_at</code>. Optional: fees, currency, status, merchant, placement, offer_id, click_id and perfume_id. Duplicate source + transaction IDs are ignored safely.</p><form action={importAffiliateCommissions} className="admin-filters"><input name="source_name" required placeholder="Affiliate network / source"/><input name="file" type="file" accept=".csv,text/csv" required/><button className="button">Import Commissions</button></form></div>
  <div className="admin-card"><h2>Record revenue</h2><p className="muted">Use this for affiliate commission reports, direct sponsorship invoices, ad revenue or subscription revenue until automated provider imports are connected.</p><form action={recordRevenue} className="admin-filters"><select name="revenue_type" required><option value="affiliate">Affiliate</option><option value="sponsorship">Sponsorship</option><option value="advertising">Advertising</option><option value="subscription">Subscription</option><option value="other">Other</option></select><input name="source_name" required placeholder="Source / network"/><input name="external_id" placeholder="External transaction ID"/><input name="gross" type="number" min="0" step="0.01" required placeholder="Gross $"/><input name="fees" type="number" min="0" step="0.01" defaultValue="0" placeholder="Fees $"/><input name="currency" defaultValue="USD" maxLength={3}/><select name="status"><option value="pending">Pending</option><option value="confirmed">Confirmed</option><option value="paid">Paid</option><option value="refunded">Refunded</option><option value="void">Void</option></select><input name="occurred_at" type="datetime-local"/><input name="notes" placeholder="Notes"/><button className="button">Record Revenue</button></form></div>
  <div className="admin-card"><h2>Create sponsorship campaign</h2><form action={createSponsorship} className="admin-filters"><input name="name" required placeholder="Campaign name"/><input name="sponsor_name" required placeholder="Sponsor"/><input name="placement" required placeholder="Placement, e.g. homepage_banner"/><input name="destination_url" type="url" placeholder="https://…"/><input name="budget" type="number" min="0" step="0.01" placeholder="Budget $"/><input name="currency" defaultValue="USD" maxLength={3}/><input name="starts_at" type="datetime-local"/><input name="ends_at" type="datetime-local"/><select name="status"><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><input name="disclosure_label" defaultValue="Sponsored" placeholder="Disclosure label"/><button className="button">Create Campaign</button></form></div>
  {!configured&&<div className="empty-state"><h2>Revenue reporting is not connected in this environment.</h2><p>Configure the server-only Supabase service role to read protected financial records. Public site functionality is unaffected.</p></div>}
  <div className="admin-stats"><span><b>{money(summary.grossCents)}</b>Gross tracked revenue</span><span><b>{money(summary.netCents)}</b>Net tracked revenue</span><span><b>{money(summary.feeCents)}</b>Tracked fees</span><span><b>{clickCount}</b>Affiliate outbound clicks</span><span><b>{activeCampaigns.length}</b>Active / scheduled sponsors</span></div>
  <p className="muted">Affiliate clicks are traffic signals, not sales. Revenue totals include only imported or recorded monetization transactions and exclude refunded or void transactions.</p>
  <div className="admin-card"><h2>On-screen profit &amp; loss</h2><form method="get" className="admin-filters"><select name="report" defaultValue={preset}><option value="month">This month</option><option value="quarter">This quarter</option><option value="year">This year</option></select><input name="from" type="date" defaultValue={reportRange.from}/><input name="to" type="date" defaultValue={reportRange.to}/><button className="button">View P&amp;L</button></form><p className="muted">{reportRange.from} through {reportRange.to}</p><div className="admin-stats"><span><b>{money(reportPnl.grossCents,goalSettings?.currency||'USD')}</b>Gross revenue</span><span><b>{money(reportPnl.feeCents,goalSettings?.currency||'USD')}</b>Revenue fees</span><span><b>{money(reportPnl.netRevenueCents,goalSettings?.currency||'USD')}</b>Net revenue</span><span><b>{money(reportPnl.expenseCents,goalSettings?.currency||'USD')}</b>Operating expenses</span><span><b>{money(reportPnl.profitCents,goalSettings?.currency||'USD')}</b>Operating profit</span><span><b>{(reportPnl.profitMargin*100).toFixed(1)}%</b>Profit margin</span></div><div className="admin-record-meta">{reportPnl.revenueByStream.map(([name,value])=><span key={'r-'+name}>{name}: {money(value,goalSettings?.currency||'USD')}</span>)}{reportPnl.expensesByCategory.map(([name,value])=><span key={'e-'+name}>{name} expense: {money(value,goalSettings?.currency||'USD')}</span>)}</div></div>
  <div className="admin-card"><h2>Financial reports</h2><p className="muted">Choose a date range for bookkeeping exports. Expense CSV contains the underlying expense ledger; P&amp;L summarizes revenue, fees, expenses and operating profit.</p><form method="get" className="admin-filters"><input name="from" type="date" aria-label="Report start date"/><input name="to" type="date" aria-label="Report end date"/><button className="button ghost" formAction="/admin/monetization/expenses/export" formMethod="get">Export expenses CSV</button><button className="button ghost" formAction="/admin/monetization/pnl" formMethod="get">Export P&amp;L CSV</button></form></div>
  <div className="admin-card"><h2>Record operating expense</h2><p className="muted">Track Scentmarked operating costs so Revenue Center can report profit instead of revenue alone.</p><form action={recordExpense} className="admin-filters"><select name="category" required><option value="hosting">Hosting</option><option value="software">Software</option><option value="marketing">Marketing</option><option value="contractor">Contractor</option><option value="legal">Legal</option><option value="accounting">Accounting</option><option value="content">Content</option><option value="other">Other</option></select><input name="vendor" placeholder="Vendor"/><input name="description" placeholder="Description"/><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Amount $"/><input name="currency" defaultValue="USD" maxLength={3}/><input name="incurred_at" type="date"/><button className="button">Record Expense</button></form></div>
  <div className="admin-card"><h2>Profitability this month</h2><div className="admin-stats"><span><b>{money(trends.currentNetCents,goalSettings?.currency||'USD')}</b>Net revenue</span><span><b>{money(profitability.expenseCents,goalSettings?.currency||'USD')}</b>Operating expenses</span><span><b>{money(profitability.profitCents,goalSettings?.currency||'USD')}</b>Operating profit</span><span><b>{(profitability.profitMargin*100).toFixed(1)}%</b>Profit margin</span><span><b>{profitability.expenses}</b>Expense records</span></div>{profitability.byCategory.length>0&&<div className="admin-record-meta">{profitability.byCategory.map(x=><span key={x.category}>{x.category}: {money(x.amountCents,goalSettings?.currency||'USD')}</span>)}</div>}</div>
  <div className="admin-card"><h2>Recent expenses</h2>{expenses.length?<div className="admin-list">{expenses.slice(0,20).map((expense:any)=><article key={expense.id}><form action={updateExpense} className="admin-filters"><input type="hidden" name="id" value={expense.id}/><select name="category" defaultValue={expense.category}><option value="hosting">Hosting</option><option value="software">Software</option><option value="marketing">Marketing</option><option value="contractor">Contractor</option><option value="legal">Legal</option><option value="accounting">Accounting</option><option value="content">Content</option><option value="other">Other</option></select><input name="vendor" defaultValue={expense.vendor||''} placeholder="Vendor"/><input name="description" defaultValue={expense.description||''} placeholder="Description"/><input name="amount" type="number" min="0.01" step="0.01" defaultValue={(Number(expense.amount_cents||0)/100).toFixed(2)}/><input name="currency" defaultValue={expense.currency||'USD'} maxLength={3}/><input name="incurred_at" type="date" defaultValue={expense.incurred_at}/><button className="button ghost">Save</button></form><form action={deleteExpense}><input type="hidden" name="id" value={expense.id}/><button className="button ghost">Delete</button></form></article>)}</div>:<p className="muted">No operating expenses recorded yet.</p>}</div>
  <h2>Monthly profit history</h2><div className="admin-list">{[...profitHistory].reverse().map(row=><article key={row.month}><div><small>{new Date(row.month+'-01T00:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</small><h2>{money(row.profitCents,goalSettings?.currency||'USD')} operating profit</h2><div className="admin-record-meta"><span>{money(row.revenueCents,goalSettings?.currency||'USD')} net revenue</span><span>{money(row.expenseCents,goalSettings?.currency||'USD')} expenses</span><span>{(row.margin*100).toFixed(1)}% margin</span><span>{row.topExpenseCategory?`Largest cost: ${row.topExpenseCategory} (${money(row.topExpenseCents,goalSettings?.currency||'USD')})`:'No expenses'}</span></div></div></article>)}</div>
  <div className="admin-card"><h2>Monthly revenue goal</h2><div className="admin-stats"><span><b>{money(goal.goalCents,goalSettings?.currency||'USD')}</b>Monthly target</span><span><b>{(goal.progress*100).toFixed(1)}%</b>Goal progress</span><span><b>{money(goal.projectedCents,goalSettings?.currency||'USD')}</b>Projected month-end</span><span><b>{money(goal.dailyNeededCents,goalSettings?.currency||'USD')}</b>Daily pace needed</span><span><b>{goal.onPace?'On pace':'Below pace'}</b>{goal.daysRemaining} days remaining</span></div><form action={updateRevenueGoal} className="admin-filters"><input name="monthly_goal" type="number" min="0" step="0.01" defaultValue={(goal.goalCents/100).toFixed(2)} aria-label="Monthly revenue goal"/><input name="currency" defaultValue={goalSettings?.currency||'USD'} maxLength={3} aria-label="Goal currency"/><button className="button ghost">Save monthly goal</button></form></div>
  <h2>Monthly performance history</h2><div className="admin-list">{[...history].reverse().map(row=><article key={row.month}><div><small>{new Date(row.month+'-01T00:00:00Z').toLocaleDateString('en-US',{month:'long',year:'numeric',timeZone:'UTC'})}</small><h2>{money(row.netCents,goalSettings?.currency||'USD')} net revenue</h2><div className="admin-record-meta"><span>{row.transactions} transaction{row.transactions===1?'':'s'}</span><span>{row.changeRate===null?'First tracked month':`${row.changeRate>=0?'+':''}${(row.changeRate*100).toFixed(1)}% vs prior month`}</span><span>{row.goalCents===null?'No saved goal':`Goal ${money(row.goalCents,goalSettings?.currency||'USD')}`}</span><span>{row.goalHit===null?'Goal status unavailable':row.goalHit?'Goal reached':'Goal not reached'}</span></div></div></article>)}</div>
  <h2>Revenue forecast by stream</h2><div className="admin-list">{streamForecast.map(stream=><article key={stream.type}><div><small>{stream.type.toUpperCase()}</small><h2>{money(stream.monthToDateCents,goalSettings?.currency||'USD')} month to date</h2><div className="admin-record-meta"><span>{(stream.share*100).toFixed(1)}% of current revenue</span><span>{stream.transactions} transaction{stream.transactions===1?'':'s'}</span><span>{money(stream.projectedCents,goalSettings?.currency||'USD')} projected month-end</span><span>{goal.goalCents?((stream.projectedCents/goal.goalCents)*100).toFixed(1):'0.0'}% of monthly target projected</span></div></div></article>)}</div><p className="muted">Forecasts extend each stream's current month-to-date net revenue pace through the end of the month. They are directional projections, not guaranteed future revenue.</p>
  <h2>Revenue momentum</h2><div className="admin-stats"><span><b>{money(trends.currentNetCents)}</b>This month net</span><span><b>{money(trends.previousNetCents)}</b>Previous month net</span><span><b>{trends.growthRate>=0?'+':''}{(trends.growthRate*100).toFixed(1)}%</b>Month-over-month</span><span><b>{money(trends.realizedCents)}</b>Confirmed / paid net</span><span><b>{money(trends.pendingCents)}</b>Pending net</span></div><p className="muted">{trends.currentTransactions} monetization transaction{trends.currentTransactions===1?'':'s'} this month versus {trends.previousTransactions} last month. Month-over-month compares net revenue after tracked fees and excludes refunded or void transactions.</p>
  <h2>Affiliate data quality</h2><div className="admin-stats"><span><b>{affiliateQuality.total}</b>Commission records</span><span><b>{affiliateQuality.fullyAttributed}</b>Fully attributed</span><span><b>{affiliateQuality.unattributed}</b>Need attribution</span><span><b>{(affiliateQuality.attributionRate*100).toFixed(1)}%</b>Attribution rate</span></div><p className="muted">A fully attributed commission has a tracked click, offer, merchant, perfume and placement. Incomplete records still count as revenue but cannot support every performance breakdown.</p>
  <h3>Reconciliation queue</h3><div className="admin-stats"><span><b>{reconciliation.complete}</b>Complete</span><span><b>{reconciliation.enrichable}</b>Safe to auto-fill</span><span><b>{reconciliation.conflict}</b>Conflicts — review</span><span><b>{reconciliation.unresolved}</b>Unresolved</span></div><p className="muted">Only records backed by exact click or offer tracking are eligible for automatic enrichment. Conflicting imported values stay untouched for manual review.</p>{affiliateQuality.unattributed>0&&<div className="admin-filters"><Link className="button ghost" href="/admin/monetization/review">Review commissions</Link><a className="button ghost" href="/admin/monetization/reconciliation">Export review queue</a>{reconciliation.enrichable>0&&<form action="/admin/monetization/reconcile" method="post"><button className="button ghost">Auto-fill {reconciliation.enrichable} exact match{reconciliation.enrichable===1?'':'es'}</button></form>}</div>}
  <div className="admin-heading"><div><h2>Top affiliate revenue drivers</h2><p className="muted">Rankings for the selected reporting period.</p></div><div className="admin-filters"><Link className="button ghost" href="/admin/monetization?period=7d">7 days</Link><Link className="button ghost" href="/admin/monetization?period=30d">30 days</Link><Link className="button ghost" href="/admin/monetization?period=90d">90 days</Link><Link className="button ghost" href="/admin/monetization?period=all">All time</Link><a className="button ghost" href={'/admin/monetization/export?period='+period}>Export CSV</a></div></div><div className="admin-card"><h3>Networks / sources</h3><div className="admin-list">{topSources.length?topSources.map(x=><div key={x.key}><b>{x.key}</b><span>{money(x.netCents)} net · {x.transactions} commission{x.transactions===1?'':'s'}</span></div>):<p className="muted">No attributed affiliate revenue yet.</p>}</div><h3>Merchants</h3><div className="admin-list">{topMerchants.length?topMerchants.map(x=><div key={x.key}><b>{x.key}</b><span>{money(x.netCents)} net · {x.transactions} commission{x.transactions===1?'':'s'}</span></div>):<p className="muted">Merchant attribution will appear after commission imports are reconciled.</p>}</div><h3>Placements</h3><div className="admin-list">{topPlacements.length?topPlacements.map(x=><div key={x.key}><b>{x.key}</b><span>{money(x.netCents)} net · {x.transactions} commission{x.transactions===1?'':'s'}</span></div>):<p className="muted">Placement attribution will appear after tracked clicks are matched to commissions.</p>}</div><h3>Perfumes</h3><div className="admin-list">{topPerfumes.length?topPerfumes.map(x=><div key={x.key}><b>{perfumeNames.get(x.key)||x.key}</b><span>{money(x.netCents)} net · {x.transactions} commission{x.transactions===1?'':'s'}</span></div>):<p className="muted">Perfume revenue rankings will appear after commissions are attributed to fragrances.</p>}</div></div>
  <p className="muted">Rankings use net affiliate revenue after tracked fees and exclude refunded, void, and unattributed records from dimensions they cannot support.</p>
  <h2>Affiliate conversion funnel</h2><div className="admin-stats"><span><b>{affiliate.clicks}</b>Tracked clicks</span><span><b>{affiliate.conversions}</b>Recorded conversions</span><span><b>{(affiliate.conversionRate*100).toFixed(2)}%</b>Conversion rate</span><span><b>{money(affiliate.epcCents)}</b>Earnings per click</span><span><b>{money(affiliate.averageCommissionCents)}</b>Average commission</span></div><p className="muted">Conversion metrics become meaningful as affiliate network sale/commission reports are imported. A click alone is never counted as a conversion.</p>
  <h2>Revenue streams</h2>
  <div className="admin-stats">{types.map(type=><span key={type}><b>{money(summary.byType.get(type)||0)}</b>{type[0].toUpperCase()+type.slice(1)}</span>)}</div>
  <div className="admin-card"><h2>Grant premium access</h2><p className="muted">For testing, staff, promotions or complimentary access. Manual grants do not represent a payment.</p><form action={grantMembership} className="admin-filters"><input name="email" type="email" required placeholder="Member email"/><select name="plan_id" required><option value="">Choose premium plan</option>{plans.filter((x:any)=>x.is_active&&x.slug!=='free').map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input name="days" type="number" min="1" max="3660" defaultValue="30" aria-label="Access days"/><button className="button">Grant Access</button></form></div>
  <h2>Membership</h2><div className="admin-stats"><span><b>{premiumMembers}</b>Active / trialing premium members</span><span><b>{plans.filter((x:any)=>x.is_active).length}</b>Active plans</span><span><b>{membershipStats.trialing}</b>Trials</span><span><b>{membershipStats.manual}</b>Manual grants</span><span><b>{membershipStats.pastDue}</b>Past due</span><span><b>{membershipStats.cancelAtPeriodEnd}</b>Ending at period close</span></div><div className="admin-list">{plans.map((plan:any)=><article key={plan.id}><form action={updateMembershipPlan} className="admin-filters"><input type="hidden" name="id" value={plan.id}/><label>Plan<input name="name" defaultValue={plan.name} required/></label><label>Price<input name="price" type="number" min="0" step="0.01" defaultValue={(Number(plan.price_cents||0)/100).toFixed(2)}/></label><label>Billing<select name="billing_interval" defaultValue={plan.billing_interval}><option value="month">Monthly</option><option value="year">Yearly</option><option value="one_time">One time</option></select></label><label>Currency<input name="currency" defaultValue={plan.currency} maxLength={3}/></label><label>Entitlements<input name="entitlements" defaultValue={(plan.entitlements||[]).join(', ')}/></label><label>Description<input name="description" defaultValue={plan.description||''}/></label><label><input name="is_active" type="checkbox" defaultChecked={plan.is_active}/> Active</label><button className="button ghost">Save {plan.slug}</button></form></article>)}</div>{subscriptions.filter((x:any)=>x.provider==='manual'&&['trialing','active'].includes(x.status)).length>0&&<><h3>Manual premium access</h3><div className="admin-list">{subscriptions.filter((x:any)=>x.provider==='manual'&&['trialing','active'].includes(x.status)).map((x:any)=><article key={x.id}><div><b>Member {String(x.user_id).slice(0,8)}…</b><small>{x.status.toUpperCase()} · ends {x.current_period_end?new Date(x.current_period_end).toLocaleDateString():'No end date'}</small></div><form action={endManualMembership}><input type="hidden" name="id" value={x.id}/><button className="button ghost">End access</button></form></article>)}</div></>}<p className="muted">Plan settings define access and display pricing only. No payment provider is connected yet, so changing a price here cannot charge a member.</p>
  <h2>Sponsorship performance</h2><div className="admin-stats"><span><b>{sponsorImpressions}</b>Impressions</span><span><b>{sponsorClicks}</b>Clicks</span><span><b>{(sponsorCtr*100).toFixed(2)}%</b>CTR</span></div>
  <h2>Sponsorship inventory</h2>
  <div className="admin-list">{campaigns.length?campaigns.map((x:any)=><article key={x.id}><div><small>{x.status.toUpperCase()} · {x.placement}</small><h2>{x.name}</h2><div className="admin-record-meta"><span>{x.sponsor_name}</span>{x.budget_cents!=null&&<span>{money(x.budget_cents,x.currency)} budget</span>}</div></div><form action={updateSponsorshipStatus} className="admin-filters"><input type="hidden" name="id" value={x.id}/><select name="status" defaultValue={x.status}><option value="draft">Draft</option><option value="scheduled">Scheduled</option><option value="active">Active</option><option value="paused">Paused</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><button className="button ghost">Update</button></form></article>):<div className="empty-state"><h2>No sponsorship campaigns yet.</h2><p>The infrastructure is ready for direct sponsored placements without changing fragrance recommendation scores.</p></div>}</div>
 </section></main>
}
