import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'

type Search={q?:string;brand?:string;type?:string;note?:string;accord?:string;sort?:string;page?:string}
const middleEastern=['Lattafa','Maison Alhambra','Paris Corner','French Avenue','Khadlaj','Swiss Arabian','Armaf','Afnan','Rasasi','Al Haramain']
const niche=['Giardini di Toscana','Maison Francis Kurkdjian','Parfums de Marly','Xerjoff','Mancera','Montale','Kilian Paris','Nishane','Initio']
const segment=(brand:string)=>middleEastern.includes(brand)?'Middle Eastern':niche.includes(brand)?'Niche':'Designer'
export const metadata={title:'Discover Fragrances',description:'Search and filter the Scentmarked fragrance catalog by brand, note and fragrance collection.',alternates:{canonical:'/discover'},openGraph:{title:'Discover Fragrances | Scentmarked',description:'Search designer, Middle Eastern and niche fragrances by brand, note and accord.',url:'/discover',type:'website'}}

export default async function Discover({searchParams}:{searchParams:Promise<Search>}){
 const p=await searchParams;let all:any[]=[],relationships:any[]=[],offerPerfumes=new Set<string>(),loadError=false
 try{const s=await createClient();const [result,rels,offers]=await Promise.all([s.from('perfumes').select('id,name,slug,image_url,concentration,release_year,created_at,brands(name),perfume_notes(notes(name)),perfume_accords(strength,accords(name)),ratings(overall)').eq('status','published').order('name'),s.from('scent_relationships').select('source_perfume_id,target_perfume_id,relationship_type,confidence,evidence_source'),s.from('perfume_affiliate_offers').select('perfume_id').eq('is_active',true)]);if(result.error)loadError=true;else all=(result.data||[]) as any[];if(!rels.error)relationships=rels.data||[];if(!offers.error)offerPerfumes=new Set((offers.data||[]).map((x:any)=>String(x.perfume_id)))}catch{loadError=true}
 const brands=[...new Set(all.map(x=>x.brands?.name).filter(Boolean))].sort(),q=(p.q||'').trim().toLowerCase(),note=(p.note||'').trim().toLowerCase(),accord=(p.accord||'').trim().toLowerCase()
 let data=all.filter(x=>{const brand=x.brands?.name||'',notes=(x.perfume_notes||[]).map((y:any)=>y.notes?.name).filter(Boolean),accords=(x.perfume_accords||[]).map((y:any)=>y.accords?.name).filter(Boolean);return(!q||(`${x.name} ${brand} ${notes.join(' ')} ${accords.join(' ')}`).toLowerCase().includes(q))&&(!p.brand||brand===p.brand)&&(!p.type||segment(brand)===p.type)&&(!note||notes.some((z:string)=>z.toLowerCase().includes(note)))&&(!accord||accords.some((z:string)=>z.toLowerCase().includes(accord)))})
 const relationshipPriority=(r:any)=>r?.relationship_type==='manufacturer_inspired_by'?5:r?.relationship_type==='possible_clone'?4:r?.relationship_type==='similar_dna'?3:r?.relationship_type==='community_comparison'?2:r?.relationship_type==='flanker'?1:0
 const relationshipFor=(id:string)=>relationships.filter((r:any)=>r.source_perfume_id===id||r.target_perfume_id===id).sort((a:any,b:any)=>relationshipPriority(b)-relationshipPriority(a)||(Number(b.confidence)||0)-(Number(a.confidence)||0))[0]
 const relationshipLabel=(r:any)=>r?.relationship_type==='manufacturer_inspired_by'?'Documented inspiration':r?.relationship_type==='possible_clone'?'Possible clone':r?.relationship_type==='similar_dna'?'Similar DNA':r?.relationship_type==='flanker'?'Fragrance family':'Known comparison'
 const relatedPerfume=(id:string,r:any)=>{if(!r)return null;const otherId=r.source_perfume_id===id?r.target_perfume_id:r.source_perfume_id;return all.find((x:any)=>x.id===otherId)||null}
 const evidenceUrl=(value:any)=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
 const rating=(x:any)=>{const r=(x.ratings||[]).map((v:any)=>Number(v.overall)).filter(Boolean);return r.length?r.reduce((a:number,b:number)=>a+b,0)/r.length:0}
 if(p.sort==='rating')data.sort((a,b)=>rating(b)-rating(a)||(b.ratings?.length||0)-(a.ratings?.length||0))
 else if(p.sort==='newest')data.sort((a,b)=>(b.release_year||0)-(a.release_year||0)||a.name.localeCompare(b.name))
 else if(p.sort==='az')data.sort((a,b)=>a.name.localeCompare(b.name))
 const total=data.length,pageSize=24,totalPages=Math.max(1,Math.ceil(total/pageSize)),requested=Number.parseInt(p.page||'1',10),page=Math.min(totalPages,Math.max(1,Number.isFinite(requested)?requested:1)),start=(page-1)*pageSize
 data=data.slice(start,start+pageSize)
 const pageHref=(n:number)=>{const params=new URLSearchParams();for(const [k,v] of Object.entries(p)){if(k!=='page'&&v)params.set(k,v)}if(n>1)params.set('page',String(n));const qs=params.toString();return '/discover'+(qs?'?'+qs:'')}
 return <main><section className="discover-page"><div className="discover-banner"><p className="eyebrow">SCENT LIBRARY</p><h1>Discover Fragrances</h1><p>Explore designer, Middle Eastern and niche scents by house, note and fragrance style.</p><form action="/discover"><span>⌕</span><input name="q" defaultValue={p.q} placeholder="Search perfume, brand, note, or vibe…"/><button className="button">Search</button></form></div>
 <section className="community-consensus"><p className="eyebrow">PERSONALIZED DISCOVERY</p><h2>Not sure what to search for?</h2><p>Tell ScentMarked the notes and scent families you love, what you want to avoid, your preferred wear profile, and budget. You can get recommendations without choosing a starting perfume.</p><div className="rating-actions"><Link className="button" href="/matches">Build My Scent Match</Link></div></section>
 <form action="/discover" className="discover-tools"><select name="type" defaultValue={p.type||''}><option value="">All Collections</option><option>Middle Eastern</option><option>Designer</option><option>Niche</option></select><select name="brand" defaultValue={p.brand||''}><option value="">All Brands</option>{brands.map(brand=><option key={brand} value={brand}>{brand}</option>)}</select><input name="q" type="hidden" value={p.q||''}/><input name="note" defaultValue={p.note} placeholder="Filter by note"/><input name="accord" defaultValue={p.accord} placeholder="Filter by accord"/><select name="sort" defaultValue={p.sort||''}><option value="">Catalog order</option><option value="az">A–Z</option><option value="newest">Newest release</option><option value="rating">Community rating</option></select><button type="submit">Apply</button><span>{total} scents</span></form>
 {(q||p.brand||p.type||note||accord||p.sort)&&<div className="active-filters"><span>{note?'Note: '+p.note:accord?'Scent family: '+p.accord:p.brand?'Brand: '+p.brand:p.type?'Collection: '+p.type:q?'Search: '+p.q:'Showing filtered results'}</span><div className="result-actions">{(note||accord)&&<Link href={'/matches?love='+encodeURIComponent(String(p.note||p.accord||''))}>Find Matches Like This →</Link>}<Link href="/discover">Clear all ×</Link></div></div>}
 {loadError?<div className="empty-state"><h2>The scent library is temporarily unavailable.</h2><p>Please refresh in a moment.</p></div>:!data.length?<div className="empty-state"><h2>No fragrances match those filters.</h2><p>Try a broader search, another brand, or clear the current filters.</p>{(note||accord)&&<Link className="text-link" href={'/matches?love='+encodeURIComponent(String(p.note||p.accord||''))}>Try personalized matches for {p.note||p.accord} →</Link>}<Link className="button" href="/discover">Clear Filters</Link></div>:<div className="discover-grid">{data.map(x=>{const brand=x.brands?.name||'',notes=(x.perfume_notes||[]).map((y:any)=>y.notes?.name).filter(Boolean),accords=(x.perfume_accords||[]).filter((y:any)=>y.accords?.name).sort((a:any,b:any)=>(b.strength||0)-(a.strength||0)).map((y:any)=>y.accords.name),avg=rating(x),count=x.ratings?.length||0,relationship=relationshipFor(x.id),related=relatedPerfume(x.id,relationship);return <article key={x.id}><Link className="discover-bottle product-profile-link" href={"/perfume/"+x.slug}>{x.image_url?<img src={x.image_url} alt={x.name+" by "+brand} loading="lazy"/>:<div className="catalog-placeholder"><small>{brand||"Scentmarked"}</small><b>{x.name}</b></div>}<i>♡</i></Link><small>{brand}</small><Link href={'/perfume/'+x.slug}><h3>{x.name}</h3></Link><p className="meta-line">{segment(brand)} · {x.concentration||'Fragrance'}</p>{relationship&&<div className="relationship-empty"><b>⚠ {relationshipLabel(relationship)}{related?' · '+related.name:''}</b>{relationship.confidence!=null&&<small>Evidence confidence: {Number(relationship.confidence)}%</small>}{relationship.evidence_source&&(evidenceUrl(relationship.evidence_source)?<a className="text-link" href={evidenceUrl(relationship.evidence_source)!} target="_blank" rel="noreferrer">{relationship.relationship_type==='manufacturer_inspired_by'?'View manufacturer evidence ↗':'View relationship evidence ↗'}</a>:<small>{relationship.relationship_type==='manufacturer_inspired_by'?'Manufacturer evidence':'Relationship evidence'} recorded</small>)}{related&&<Link className="text-link" href={'/compare?a='+x.slug+'&b='+related.slug}>Compare both →</Link>}</div>}{avg>0&&<p className="stars">★ <b>{avg.toFixed(1)}</b> <em>{count} rating{count===1?'':'s'}</em></p>}<div className="note-chips">{notes.slice(0,3).map((n:string)=><Link href={'/discover?note='+encodeURIComponent(n)} key={'n-'+n}>{n}</Link>)}{accords.slice(0,2).map((a:string)=><Link className="accord-chip" href={'/discover?accord='+encodeURIComponent(a)} key={'a-'+a}>{a} accord</Link>)}</div><div className="result-actions"><Link className="view-scent" href={'/perfume/'+x.slug+(offerPerfumes.has(String(x.id))?'#where-to-buy':'')}>{offerPerfumes.has(String(x.id))?'VIEW SCENT + RETAILERS':'VIEW SCENT'}</Link><Link href={'/matches?perfume='+x.slug}>FIND SIMILAR →</Link></div></article>})}</div>}
 {!loadError&&totalPages>1&&<nav className="pagination" aria-label="Fragrance results pages"><Link className={page===1?'disabled':''} aria-disabled={page===1} href={pageHref(Math.max(1,page-1))}>← Previous</Link><span>Page {page} of {totalPages}</span><Link className={page===totalPages?'disabled':''} aria-disabled={page===totalPages} href={pageHref(Math.min(totalPages,page+1))}>Next →</Link></nav>}
 </section></main>
}
