import Link from 'next/link'
import AffiliateLink from '@/components/affiliate-link'
import { notFound, permanentRedirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import MarkScent from '@/components/mark-scent'
import RateScent from '@/components/rate-scent'
import ProfileQuickActions from '@/components/profile-quick-actions'
import { siteUrl } from '@/lib/site'
import { validAffiliateUrl } from '@/lib/affiliate-tracking'
import TasteBadge from '@/components/taste-badge'

export const dynamic = 'force-dynamic'

const publicText=(value:any,max=160)=>typeof value==='string'?value.trim().replace(/\s+/g,' ').slice(0,max):''
const safeImageUrl=(value:any)=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params
 try{const s=await createClient();const {data}=await s.from('perfumes').select('name,description,image_url,brands(name)').eq('slug',slug).eq('status','published').maybeSingle();const name=publicText(data?.name,120);if(name){const brand=publicText((data?.brands as any)?.name,100),description=publicText(data?.description,300),image=safeImageUrl(data?.image_url),title=`${name}${brand?' by '+brand:''}`;return{title,description:description||`Explore verified notes, scent DNA, ratings and similar fragrances for ${name} on Scentmarked.`,alternates:{canonical:'/perfume/'+encodeURIComponent(slug)},openGraph:{title,description:description||`Explore ${name} fragrance notes and scent profile on Scentmarked.`,type:'website',url:'/perfume/'+encodeURIComponent(slug),images:image?[{url:image,alt:title}]:undefined}}}}catch{}
 return{title:'Fragrance Profile',robots:{index:false,follow:true}}
}
export default async function PerfumePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;let s:any;let result:any
 try{s=await createClient();result=await s.from('perfumes').select('id,name,slug,description,image_url,concentration,release_year,country,gender_marketing,price_low,price_high,brands(name,slug),perfume_notes(position,notes(name,slug)),perfume_accords(strength,accords(name,slug))').eq('slug',slug).eq('status','published').maybeSingle()}catch{return <main className="profile-page"><section className="empty-state"><h1>Fragrance profile temporarily unavailable</h1><p>Please try again in a moment.</p><Link className="button" href="/discover">Discover Fragrances</Link></section></main>}
 if(result.error)return <main className="profile-page"><section className="empty-state"><h1>Fragrance profile temporarily unavailable</h1><p>The fragrance data could not be loaded. Please try again in a moment.</p><Link className="button" href="/discover">Discover Fragrances</Link></section></main>
 // Prefer canonical profiles even while legacy duplicate records remain in the catalog.
 try{
  const alias=await s.from('perfume_aliases').select('perfume_id').eq('alias_slug',slug).maybeSingle()
  if(!alias.error&&alias.data?.perfume_id){
   const canonical=await s.from('perfumes').select('slug').eq('id',alias.data.perfume_id).eq('status','published').maybeSingle()
   if(!canonical.error&&canonical.data?.slug&&canonical.data.slug!==slug){
    permanentRedirect('/perfume/'+encodeURIComponent(canonical.data.slug))
   }
  }
 }catch(error){if(error&&typeof error==='object'&&'digest' in error)throw error}
 if(!result.data)notFound()
 const p:any=result.data;let fallbackImage:any=null;try{const now=new Date().toISOString(),r=await s.from('site_content').select('image_url,alt_text').eq('content_key','perfume_fallback').eq('is_active',true).or('starts_at.is.null,starts_at.lte.'+now).or('ends_at.is.null,ends_at.gte.'+now).maybeSingle();fallbackImage=r.data}catch{}const primaryImage=safeImageUrl(p.image_url),fallbackImageUrl=safeImageUrl(fallbackImage?.image_url),displayImage=primaryImage||fallbackImageUrl||null,notes:any[]=p.perfume_notes||[],accords:any[]=Array.from((p.perfume_accords||[]).reduce((map:Map<string,any>,a:any)=>{const accordName=publicText(a?.accords?.name,80),rawStrength=Number(a?.strength);if(!accordName||!Number.isFinite(rawStrength)||rawStrength<=0)return map;const strength=Math.max(0,Math.min(100,rawStrength)),key=accordName.toLocaleLowerCase(),existing=map.get(key);if(!existing||strength>existing.strength)map.set(key,{...a,strength,accords:{...a.accords,name:accordName}});return map},new Map<string,any>()).values()),name=publicText(p.name,120)||'Fragrance',description=publicText(p.description,1200),brand=publicText(p.brands?.name,100)||'Scentmarked',brandSlug=publicText(p.brands?.slug,200),profileSlug=publicText(p.slug,200)||slug
 const accordStrength=(value:any)=>Math.max(0,Math.min(100,Number(value)))
 const heroNotes=notes.map((n:any)=>n.notes).filter((n:any)=>typeof n?.name==='string'&&n.name.trim()).map((n:any)=>({...n,name:n.name.trim()})).filter((n:any,i:number,list:any[])=>list.findIndex((x:any)=>x.name.toLowerCase()===n.name.toLowerCase())===i).slice(0,5)
 let ratings:any[]=[];try{const rr=await s.from('ratings').select('overall,longevity,projection,sweetness,review,created_at,user_id').eq('perfume_id',p.id);if(!rr.error)ratings=rr.data||[]}catch{}
 let initialMarks:string[]=[];try{const {data:{user}}=await s.auth.getUser();if(user){const [marks]=await Promise.all([s.from('collection_items').select('status').eq('user_id',user.id).eq('perfume_id',p.id),s.from('recently_viewed_perfumes').upsert({user_id:user.id,perfume_id:p.id,viewed_at:new Date().toISOString()},{onConflict:'user_id,perfume_id'})]);if(!marks.error)initialMarks=(marks.data||[]).map((x:any)=>x.status).filter((x:any):x is string=>typeof x==='string')}}catch{}
 const favorite=initialMarks.includes('favorite')
 const validScore=(value:any)=>Number.isFinite(Number(value))&&Number(value)>=1&&Number(value)<=5
 const overallRatings=ratings.filter((r:any)=>validScore(r.overall))
 const avg=overallRatings.length?(overallRatings.reduce((a:number,r:any)=>a+Number(r.overall),0)/overallRatings.length).toFixed(1):null
 const metric=(key:string)=>{const rows=ratings.filter((r:any)=>validScore(r[key]));return rows.length?(rows.reduce((a:number,r:any)=>a+Number(r[key]),0)/rows.length).toFixed(1):null}
 const longevity=metric('longevity'),projection=metric('projection'),sweetness=metric('sweetness')
 const performanceMetrics:{key:string;label:string;value:string|null;icon:string}[]=[{key:'longevity',label:'Longevity',value:longevity,icon:'◷'},{key:'projection',label:'Projection',value:projection,icon:'◎'},{key:'sweetness',label:'Sweetness',value:sweetness,icon:'◇'}]
 const metricLabel=(key:string,value:string|null)=>{if(!value)return'';const n=Number(value);if(key==='longevity')return n>=4.5?'Very long lasting':n>=3.5?'Long lasting':n>=2.5?'Moderate':n>=1.5?'Light':'Short';if(key==='projection')return n>=4.5?'Room filling':n>=3.5?'Strong':n>=2.5?'Moderate':n>=1.5?'Soft':'Intimate';return n>=4.5?'Very sweet':n>=3.5?'Sweet':n>=2.5?'Balanced':n>=1.5?'Low sweetness':'Dry'}
 let relationships:any[]=[];try{const rel=await s.from('scent_relationships').select('id,source_perfume_id,target_perfume_id,relationship_type,confidence,evidence_source').or('source_perfume_id.eq.'+p.id+',target_perfume_id.eq.'+p.id);if(!rel.error&&rel.data?.length){const ids=[...new Set(rel.data.flatMap((x:any)=>[x.source_perfume_id,x.target_perfume_id]).filter((x:any)=>x&&x!==p.id))];const related=ids.length?await s.from('perfumes').select('id,name,slug,brands(name)').in('id',ids).eq('status','published'):null;const byId=new Map((related?.data||[]).map((x:any)=>[x.id,x]));relationships=rel.data.map((x:any)=>{const item:any=byId.get(x.source_perfume_id===p.id?x.target_perfume_id:x.source_perfume_id);if(!item||!publicText(item.name)||!publicText(item.slug))return null;return{...x,related:{...item,name:publicText(item.name),slug:publicText(item.slug,200),brands:item.brands?{...item.brands,name:publicText(item.brands.name,120)}:item.brands}}}).filter(Boolean)}}catch{}
 let affiliateOffers:any[]=[];try{const r=await s.from('perfume_affiliate_offers').select('id,merchant_name,affiliate_url,price,currency,label,priority,updated_at').eq('perfume_id',p.id).eq('is_active',true).order('priority',{ascending:true});affiliateOffers=(r.data||[]).map((x:any)=>({...x,merchant_name:publicText(x?.merchant_name,100),label:publicText(x?.label,180)})).filter((x:any)=>x.merchant_name&&validAffiliateUrl(String(x.affiliate_url||'')))}catch{}
 const cloneRelationships=relationships.filter((r:any)=>['manufacturer_inspired_by','possible_clone'].includes(String(r.relationship_type||'').toLowerCase()))
 const featuredRelationship=cloneRelationships[0]||null
 const validOfferPrice=(x:any)=>x?.price!=null&&Number.isFinite(Number(x.price))&&Number(x.price)>=0
 const featuredOffer=affiliateOffers[0]||null,additionalOffers=affiliateOffers.slice(1),pricedOffers=affiliateOffers.filter(validOfferPrice),lowestRecordedPrice=pricedOffers.length?Math.min(...pricedOffers.map((x:any)=>Number(x.price))):null
 const evidenceUrl=(value:any)=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
 const formatUsd=(value:any)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:Number(value)%1===0?0:2}).format(Number(value))
 const offerPrice=(x:any)=>{if(!validOfferPrice(x))return'';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:String(x.currency||'USD').toUpperCase()}).format(Number(x.price))}catch{return formatUsd(x.price)}}
 const offerDate=(x:any)=>{if(!x.updated_at)return null;const d=new Date(x.updated_at);return Number.isNaN(d.getTime())?null:d}
 const offerUpdated=(x:any)=>{const d=offerDate(x);return d?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric'}).format(d):null}
 const offerIsStale=(x:any)=>{const d=offerDate(x);return d?Date.now()-d.getTime()>30*24*60*60*1000:false}
 let sources:any[]=[];try{const r=await s.from('perfume_sources').select('id,source_name,source_url,fields_verified,is_primary').eq('perfume_id',p.id).order('is_primary',{ascending:false});sources=(r.data||[]).map((x:any)=>({...x,source_name:publicText(x?.source_name,120),fields_verified:Array.isArray(x?.fields_verified)?x.fields_verified.map((v:any)=>publicText(v,80)).filter((v:string,i:number,list:string[])=>v&&list.findIndex((other:string)=>other.toLocaleLowerCase()===v.toLocaleLowerCase())===i).slice(0,20):[]})).filter((x:any)=>x.source_name)}catch{}
 const group=(pos:string)=>notes.filter(n=>String(n.position||'').toLowerCase()===pos).map(n=>n.notes).filter((n:any)=>typeof n?.name==='string'&&n.name.trim()).map((n:any)=>({...n,name:n.name.trim()})).filter((n:any,i:number,list:any[])=>list.findIndex((x:any)=>x.name.toLowerCase()===n.name.toLowerCase())===i)
 const cleanText=(value:any,max=200)=>typeof value==='string'?value.trim().replace(/\s+/g,' ').slice(0,max):''
 const reviewerIds=[...new Set(ratings.map((r:any)=>r.user_id).filter(Boolean))]
 const communityProfiles=reviewerIds.length?await s.from('community_profiles').select('user_id,display_name,taste_label,show_taste_badge').in('user_id',reviewerIds):null
 const communityById=new Map<string,{display_name:string|null;taste_label:string|null;show_taste_badge:boolean}>((communityProfiles?.data||[]).map((x:any)=>[String(x.user_id),x]))
 const reviewerName=(r:any)=>cleanText(communityById.get(r.user_id)?.display_name,80)||'Scentmarked member'
 const writtenReviews=ratings.map((r:any)=>({...r,cleanReview:cleanText(r.review,1000)})).filter((r:any)=>r.cleanReview).sort((a:any,b:any)=>{const at=new Date(a.created_at).getTime(),bt=new Date(b.created_at).getTime();return (Number.isFinite(bt)?bt:0)-(Number.isFinite(at)?at:0)}).slice(0,6)
 const factText=(value:any,max=80)=>typeof value==='string'?value.trim().replace(/\s+/g,' ').slice(0,max):''
 const concentration=factText(p.concentration),country=factText(p.country),genderMarketing=factText(p.gender_marketing),releaseYear=Number(p.release_year),hasReleaseYear=Number.isInteger(releaseYear)&&releaseYear>=1700&&releaseYear<=new Date().getFullYear()+1
 const lowPrice=Number(p.price_low),highPrice=Number(p.price_high),hasLow=p.price_low!=null&&Number.isFinite(lowPrice)&&lowPrice>=0,hasHigh=p.price_high!=null&&Number.isFinite(highPrice)&&highPrice>=0
 const structuredOffers=hasLow&&hasHigh&&lowPrice<=highPrice?{'@type':'AggregateOffer',priceCurrency:'USD',lowPrice,highPrice}:hasLow?{'@type':'Offer',priceCurrency:'USD',price:lowPrice}:hasHigh?{'@type':'Offer',priceCurrency:'USD',price:highPrice}:undefined
 const jsonLd={'@context':'https://schema.org','@type':'Product',name,description:description||undefined,image:displayImage||undefined,brand:{'@type':'Brand',name:brand},category:'Fragrance',url:siteUrl+'/perfume/'+encodeURIComponent(profileSlug),offers:structuredOffers,aggregateRating:avg?{'@type':'AggregateRating',ratingValue:Number(avg),ratingCount:overallRatings.length,bestRating:5,worstRating:1}:undefined}
 const jsonLdText=JSON.stringify(jsonLd).replace(/</g,'\\u003c')
 return <main className="profile-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:jsonLdText}}/><section className="profile-hero"><div className="profile-visual"><div className="profile-art">{displayImage?<img className="profile-product-image" src={displayImage} alt={primaryImage?`${name} by ${brand}`:(publicText(fallbackImage?.alt_text,160)||'ScentMarked fragrance image')} loading="eager"/>:<div className="profile-bottle catalog-placeholder"><span>{brand}</span><b>{name}</b><small>{factText(p.concentration)||'FRAGRANCE'}</small></div>}</div>{displayImage&&<div className="profile-thumbnails" aria-label="Fragrance images"><span className="active"><img src={displayImage} alt="" /></span></div>}</div><div className="profile-info"><p className="breadcrumbs"><Link href="/">Home</Link>　›　{brandSlug?<Link href={'/brand/'+encodeURIComponent(brandSlug)}>{brand}</Link>:brand}　›　{name}</p><div className="profile-title-row"><div><p className="eyebrow">{brand}</p><h1>{name}</h1></div><ProfileQuickActions perfumeId={p.id} name={name} initialFavorite={favorite}/></div>
 {avg?<p className="rating">★ {avg} <span>{overallRatings.length} community rating{overallRatings.length===1?'':'s'}</span></p>:<p className="verified-label">COMMUNITY RATING NOT YET AVAILABLE</p>}

 {['lattafa-fakhar-men','lattafa-fakhar-black'].includes(profileSlug)&&<aside className="profile-relationship-warning" role="note" aria-label="Manufacturer source discrepancy"><div><strong>Manufacturer note listings differ</strong><p>Lattafa's regional product pages publish different note pyramids for Fakhar Men and Fakhar Black. Scentmarked preserves both source-backed listings while their identity is reviewed; do not treat the listed notes as a confirmed product difference.</p><Link href={'/perfume/'+(profileSlug==='lattafa-fakhar-men'?'lattafa-fakhar-black':'lattafa-fakhar-men')}>Review the other listing →</Link></div></aside>}
 {heroNotes.length>0&&<div className="profile-tags">{heroNotes.map((n:any)=><Link href={'/discover?note='+encodeURIComponent(n.name)} key={n.slug||n.name}>{n.name}</Link>)}</div>}<p className="profile-desc">{description||'Verified scent details are being added.'}</p>{featuredRelationship&&<div className="profile-relationship-warning"><span>SCENT RELATIONSHIP</span><div><strong>{String(featuredRelationship.relationship_type).toLowerCase()==='manufacturer_inspired_by'?(featuredRelationship.source_perfume_id===p.id?'Inspired-by relationship documented':'This scent is documented as an inspiration'):'Possible clone relationship documented'}</strong><p>{featuredRelationship.related.brands?.name||'Fragrance'} · {featuredRelationship.related.name}{cloneRelationships.length>1?' · +'+(cloneRelationships.length-1)+' more relationship'+(cloneRelationships.length-1===1?'':'s'):''}</p></div><Link href={'/perfume/'+encodeURIComponent(featuredRelationship.related.slug)}>View scent →</Link><Link href={'/compare?a='+encodeURIComponent(p.slug)+'&b='+encodeURIComponent(featuredRelationship.related.slug)}>Compare →</Link></div>}<div className="profile-facts">{concentration&&<span><b>Concentration</b>{concentration}</span>}{hasReleaseYear&&<span><b>Released</b>{releaseYear}</span>}{country&&<span><b>Origin</b>{country}</span>}{genderMarketing&&<span><b>Marketed for</b>{genderMarketing}</span>}{(hasLow||hasHigh)&&<span><b>Price range</b>{hasLow&&hasHigh&&lowPrice<=highPrice?`${formatUsd(lowPrice)}–${formatUsd(highPrice)}`:hasLow?`From ${formatUsd(lowPrice)}`:`Up to ${formatUsd(highPrice)}`}</span>}</div><div className="profile-actions"><MarkScent perfumeId={p.id} initial={initialMarks}/><Link className="button" href={'/matches?perfume='+encodeURIComponent(p.slug)}>Find Similar　→</Link><Link className="button ghost" href={'/compare?a='+encodeURIComponent(p.slug)}>Compare　⇄</Link>{featuredOffer&&<a className="button ghost" href="#where-to-buy">Where to Buy　↓</a>}</div>{featuredOffer&&<p className="muted">Retailer options and affiliate disclosure are available in Where to Buy below.</p>}</div></section>
 <section className="profile-body"><div className="dna-side"><p className="eyebrow">SCENT PROFILE</p><h2>Scentmarked DNA</h2><p className="dna-intro">{sources.length>0?"Fragrance notes and accords compiled from catalog references. Check the source details below for what has been verified.":"Fragrance notes and accords are listed for discovery, but supporting source references have not yet been added. Treat these details as provisional."}</p>{accords.length?[...accords].sort((a:any,b:any)=>(b.strength||0)-(a.strength||0)).slice(0,8).map((a:any)=><div className="dna-bar" key={a.accords?.name}><span>{a.accords?.name?<Link href={'/discover?accord='+encodeURIComponent(a.accords.name)}>{a.accords.name}</Link>:''}</span><i><b style={{width:accordStrength(a.strength)+'%'}}/></i><em>{accordStrength(a.strength)}%</em></div>):<p className="muted">Accord strength data has not been verified for this fragrance yet.</p>}<p className="muted">Select a scent family to discover other fragrances with that accord.</p></div>
 <div className="notes-side"><div className="notes-heading"><p className="eyebrow">NOTE PYRAMID</p><h2>What you’ll smell</h2></div>{[['top','Top Notes','✦'],['heart','Heart Notes','❀'],['base','Base Notes','◆'],['unspecified','Other Verified Notes','◇']].map(([pos,label,icon])=>{const list=group(pos);return list.length?<div className={"note-tier note-tier-"+pos} key={pos}><div className="note-tier-title"><span>{icon}</span><h3>{label}</h3><small>{list.length} verified</small></div><div className="note-cloud">{list.map((n:any)=><Link href={'/discover?note='+encodeURIComponent(n.name)} key={n.slug||n.name}><span className="note-symbol">{icon}</span><b>{n.name}</b></Link>)}</div></div>:null})}</div></section>
 <section className="relationship-alerts"><div className="relationship-head"><div><p className="eyebrow">SCENT RELATIONSHIPS</p><h2>Clone & similarity check</h2><p>Documented relationships that can help you avoid buying a fragrance that is too close to one you already know.</p></div></div>{relationships.length?<div className="relationship-grid">{relationships.map((r:any)=>{const type=String(r.relationship_type||'').toLowerCase(),isSource=r.source_perfume_id===p.id,label=type==='manufacturer_inspired_by'?(isSource?'Manufacturer-described inspiration':'Inspires this scent'):type==='possible_clone'?'Possible clone relationship':type==='similar_dna'?'Similar DNA':type==='flanker'?'Same fragrance family':type==='community_comparison'?'Community comparison':'Related scent',warning=type==='manufacturer_inspired_by'&&isSource?'This fragrance is described by its manufacturer as inspired by the scent below.':type==='possible_clone'?'This is a documented possible-clone relationship, not a claim that the fragrances are identical.':type==='community_comparison'?'Fragrance communities or editorial sources compare these scents. It is not a manufacturer-confirmed clone claim.':null;return <article key={r.id} className={'relationship-card '+type}><span>{label}</span><div><small>{r.related.brands?.name||'Fragrance'}</small><h3>{r.related.name}</h3>{warning&&<p><strong>{warning}</strong></p>}{r.confidence!=null&&Number.isFinite(Number(r.confidence))&&<p>Evidence confidence: {Math.max(0,Math.min(100,Number(r.confidence)))}%</p>}{r.evidence_source&&(evidenceUrl(r.evidence_source)?<p><a className="text-link" href={evidenceUrl(r.evidence_source)!} target="_blank" rel="noopener noreferrer">VIEW RELATIONSHIP EVIDENCE ↗<span className="sr-only"> (opens in a new tab)</span></a></p>:<p className="muted">Evidence: {r.evidence_source}</p>)}<div className="result-actions"><Link className="text-link" href={'/perfume/'+encodeURIComponent(r.related.slug)}>VIEW PROFILE →</Link><Link className="text-link" href={'/compare?a='+encodeURIComponent(p.slug)+'&b='+encodeURIComponent(r.related.slug)}>COMPARE BOTH →</Link></div></div></article>})}</div>:<div className="relationship-empty"><b>No documented clone relationship on file.</b><p>ScentMarked does not label a fragrance as a clone based only on shared notes.</p></div>}</section>
 <section className="community-performance"><div className="performance-head"><div><p className="eyebrow">PERFORMANCE</p><h2>How it wears</h2><p>Community-reported wear data from Scentmarked members.</p></div>{overallRatings.length>0&&<span className="performance-count">{overallRatings.length} rating{overallRatings.length===1?'':'s'}</span>}</div>{(longevity||projection||sweetness)?<div className="performance-grid">{performanceMetrics.map(({key,label,value,icon})=>value?<article className="performance-card" key={key}><span className="performance-icon">{icon}</span><div><small>{label}</small><strong>{metricLabel(key,value)}</strong><div className="performance-meter" aria-label={label+' '+value+' out of 5'}><i style={{width:(Number(value)/5*100)+'%'}}/></div><em>{value}/5 community average</em></div></article>:null)}</div>:<div className="performance-empty"><b>Be one of the first to rate how it wears.</b><p>Community performance data will appear here as members rate longevity, projection, and sweetness.</p></div>}</section>
 <section className="community-love"><div className="community-love-head"><div><p className="eyebrow">COMMUNITY LOVE</p><h2>What Scentmarked members think</h2><p>Ratings and wear experiences from the fragrance community.</p></div><div className="community-score">{avg?<><strong>{avg}</strong><span className="review-stars" aria-hidden="true">{'★'.repeat(Math.round(Number(avg)))}</span><span className="sr-only">{avg} out of 5 stars. </span><small>{overallRatings.length} rating{overallRatings.length===1?'':'s'}</small></>:<><strong>—</strong><small>Not rated yet</small></>}</div></div><div className="community-rate"><RateScent perfumeId={p.id}/></div>{writtenReviews.length?<><div className="review-section-head"><h3>Member reviews</h3><Link className="text-link" href="/community">VIEW COMMUNITY →</Link></div><div className="review-grid">{writtenReviews.map((r:any,i:number)=><article key={String(r.created_at||'review')+'-'+i}>{validScore(r.overall)&&<p className="review-stars" aria-label={Number(r.overall)+' out of 5 stars'}><span aria-hidden="true">{'★'.repeat(Math.max(1,Math.min(5,Number(r.overall))))}</span></p>}<p>{r.cleanReview}</p><span className="review-author">— {reviewerName(r)}<TasteBadge label={communityById.get(r.user_id)?.taste_label} visible={communityById.get(r.user_id)?.show_taste_badge!==false}/></span></article>)}</div></>:<div className="reviews-empty"><b>No written reviews yet.</b><p>Rate this fragrance above and share your experience with the community.</p></div>}</section>
 {featuredOffer&&<section id="where-to-buy" className="source-card affiliate-offers"><div className="source-head"><div><p className="eyebrow">WHERE TO BUY</p><h2>Shop this fragrance</h2><p>Compare approved retailer options below. Some links may be affiliate links, which means ScentMarked may earn a commission at no additional cost to you. Retailer placement is separate from ScentMarked's scent-match and relationship recommendations. Prices are retailer entries stored by ScentMarked and may change; “Lowest listed here” only compares the active offers shown on this page.</p></div></div><div className="source-row featured-offer"><div><span className="source-badge primary">Featured retailer</span><strong>{featuredOffer.merchant_name}</strong>{featuredOffer.label&&<p>{featuredOffer.label}</p>}{validOfferPrice(featuredOffer)&&<p>{offerPrice(featuredOffer)}{lowestRecordedPrice!=null&&Number(featuredOffer.price)===lowestRecordedPrice?<small> · Lowest listed here</small>:null}{offerUpdated(featuredOffer)&&<small> · Price checked {offerUpdated(featuredOffer)}{offerIsStale(featuredOffer)?' · Recheck retailer':''}</small>}</p>}</div><AffiliateLink className="button" offerId={Number(featuredOffer.id)} perfumeId={p.id} placement="profile_featured" href={featuredOffer.affiliate_url}>Shop {featuredOffer.merchant_name} ↗</AffiliateLink></div>{additionalOffers.length>0&&<><h3>More retailers</h3><div className="source-list">{additionalOffers.map((x:any)=><div className="source-row" key={x.id}><div><strong>{x.merchant_name}</strong>{x.label&&<p>{x.label}</p>}{validOfferPrice(x)&&<p>{offerPrice(x)}{lowestRecordedPrice!=null&&Number(x.price)===lowestRecordedPrice?<small> · Lowest listed here</small>:null}{offerUpdated(x)&&<small> · Price checked {offerUpdated(x)}{offerIsStale(x)?' · Recheck retailer':''}</small>}</p>}</div><AffiliateLink offerId={Number(x.id)} perfumeId={p.id} placement="profile_more" href={x.affiliate_url}>Shop now ↗</AffiliateLink></div>)}</div></>}</section>}
 <section className="source-card"><div className="source-head"><div><p className="eyebrow">VERIFICATION</p><h2>Sources & verification</h2><p>References used to support the fragrance details shown on this profile.</p></div><span className="source-count">{sources.length} source{sources.length===1?'':'s'}</span></div>{sources.length?<div className="source-list">{sources.map((x:any)=><div className="source-row" key={x.id}><div><strong><span className={x.is_primary?'source-badge primary':'source-badge'}>{x.is_primary?'Primary':'Reference'}</span>{x.source_name}</strong>{(x.fields_verified||[]).length>0?<p>Verified: {(x.fields_verified||[]).join(' · ')}</p>:<p className="muted">Verified fields not specified.</p>}</div>{evidenceUrl(x.source_url)?<a href={evidenceUrl(x.source_url)!} target="_blank" rel="noopener noreferrer">View source ↗<span className="sr-only"> (opens in a new tab)</span></a>:<span className="muted">URL not provided</span>}</div>)}</div>:<div className="source-empty"><b>Verification details are being added.</b><p>Source provenance has not been published for this fragrance yet.</p></div>}</section></main>
}