import Link from 'next/link'
import { notFound } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import MarkScent from '@/components/mark-scent'
import RateScent from '@/components/rate-scent'
import ProfileQuickActions from '@/components/profile-quick-actions'

export const dynamic = 'force-dynamic'

export async function generateMetadata({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params
 try{const s=await createClient();const {data}=await s.from('perfumes').select('name,description,image_url,brands(name)').eq('slug',slug).eq('status','published').maybeSingle();if(data?.name){const brand=(data.brands as any)?.name;return{title:`${data.name}${brand?' by '+brand:''}`,description:data.description||`Explore verified notes, scent DNA, ratings and similar fragrances for ${data.name} on Scentmarked.`,alternates:{canonical:'/perfume/'+slug},openGraph:{title:`${data.name}${brand?' by '+brand:''}`,description:data.description||`Explore ${data.name} fragrance notes and scent profile on Scentmarked.`,type:'website',url:'/perfume/'+slug,images:data.image_url?[{url:data.image_url,alt:`${data.name}${brand?' by '+brand:''}`}]:undefined}}}}catch{}
 return{title:'Fragrance Profile',robots:{index:false,follow:true}}
}
export default async function PerfumePage({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;let s:any;let result:any
 try{s=await createClient();result=await s.from('perfumes').select('id,name,slug,description,image_url,concentration,release_year,country,gender_marketing,price_low,price_high,brands(name,slug),perfume_notes(position,notes(name,slug)),perfume_accords(strength,accords(name,slug))').eq('slug',slug).eq('status','published').maybeSingle()}catch{return <main className="profile-page"><section className="empty-state"><h1>Fragrance profile temporarily unavailable</h1><p>Please try again in a moment.</p><Link className="button" href="/discover">Discover Fragrances</Link></section></main>}
 if(result.error)return <main className="profile-page"><section className="empty-state"><h1>Fragrance profile temporarily unavailable</h1><p>{result.error.message||'The fragrance data could not be loaded.'}</p><Link className="button" href="/discover">Discover Fragrances</Link></section></main>
 if(!result.data)notFound()
 const p:any=result.data,notes:any[]=p.perfume_notes||[],accords:any[]=(p.perfume_accords||[]).filter((a:any)=>a?.accords?.name&&Number(a.strength)>0),brand=p.brands?.name||'Scentmarked'
 const heroNotes=notes.map((n:any)=>n.notes).filter((n:any)=>n?.name).filter((n:any,i:number,list:any[])=>list.findIndex((x:any)=>x.name===n.name)===i).slice(0,5)
 let ratings:any[]=[];try{const rr=await s.from('ratings').select('overall,longevity,projection,sweetness,review,created_at,profiles(display_name)').eq('perfume_id',p.id);if(!rr.error)ratings=rr.data||[]}catch{}
 let initialMarks:string[]=[];try{const {data:{user}}=await s.auth.getUser();if(user){const marks=await s.from('collection_items').select('status').eq('user_id',user.id).eq('perfume_id',p.id);if(!marks.error)initialMarks=(marks.data||[]).map((x:any)=>x.status).filter((x:any):x is string=>typeof x==='string')}}catch{}
 const favorite=initialMarks.includes('favorite')
 const overallRatings=ratings.filter((r:any)=>Number(r.overall)>0)
 const avg=overallRatings.length?(overallRatings.reduce((a:number,r:any)=>a+Number(r.overall),0)/overallRatings.length).toFixed(1):null
 const metric=(key:string)=>{const rows=ratings.filter((r:any)=>Number(r[key])>0);return rows.length?(rows.reduce((a:number,r:any)=>a+Number(r[key]),0)/rows.length).toFixed(1):null}
 const longevity=metric('longevity'),projection=metric('projection'),sweetness=metric('sweetness')
 const performanceMetrics:{key:string;label:string;value:string|null;icon:string}[]=[{key:'longevity',label:'Longevity',value:longevity,icon:'◷'},{key:'projection',label:'Projection',value:projection,icon:'◎'},{key:'sweetness',label:'Sweetness',value:sweetness,icon:'◇'}]
 const metricLabel=(key:string,value:string|null)=>{if(!value)return'';const n=Number(value);if(key==='longevity')return n>=4.5?'Very long lasting':n>=3.5?'Long lasting':n>=2.5?'Moderate':n>=1.5?'Light':'Short';if(key==='projection')return n>=4.5?'Room filling':n>=3.5?'Strong':n>=2.5?'Moderate':n>=1.5?'Soft':'Intimate';return n>=4.5?'Very sweet':n>=3.5?'Sweet':n>=2.5?'Balanced':n>=1.5?'Low sweetness':'Dry'}
 let relationships:any[]=[];try{const rel=await s.from('scent_relationships').select('id,source_perfume_id,target_perfume_id,relationship_type,confidence,evidence_source').or('source_perfume_id.eq.'+p.id+',target_perfume_id.eq.'+p.id);if(!rel.error&&rel.data?.length){const ids=[...new Set(rel.data.flatMap((x:any)=>[x.source_perfume_id,x.target_perfume_id]).filter((x:any)=>x&&x!==p.id))];const related=ids.length?await s.from('perfumes').select('id,name,slug,brands(name)').in('id',ids).eq('status','published'):null;const byId=new Map((related?.data||[]).map((x:any)=>[x.id,x]));relationships=rel.data.map((x:any)=>({...x,related:byId.get(x.source_perfume_id===p.id?x.target_perfume_id:x.source_perfume_id)})).filter((x:any)=>x.related)}}catch{}
 let affiliateOffers:any[]=[];try{const r=await s.from('perfume_affiliate_offers').select('id,merchant_name,affiliate_url,price,currency,label,priority').eq('perfume_id',p.id).eq('is_active',true).order('priority',{ascending:true});affiliateOffers=r.data||[]}catch{}
 const featuredOffer=affiliateOffers[0]||null,additionalOffers=affiliateOffers.slice(1)
 const evidenceUrl=(value:any)=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)?u.toString():null}catch{return null}}
 const offerPrice=(x:any)=>x.price==null?'':new Intl.NumberFormat('en-US',{style:'currency',currency:x.currency||'USD'}).format(Number(x.price))
 let sources:any[]=[];try{const r=await s.from('perfume_sources').select('id,source_name,source_url,fields_verified,is_primary').eq('perfume_id',p.id).order('is_primary',{ascending:false});sources=r.data||[]}catch{}
 const group=(pos:string)=>notes.filter(n=>n.position===pos).map(n=>n.notes).filter((n:any)=>n?.name).filter((n:any,i:number,list:any[])=>list.findIndex((x:any)=>x.name===n.name)===i)
 const reviewerName=(r:any)=>{const profile=Array.isArray(r.profiles)?r.profiles[0]:r.profiles;return profile?.display_name||'Scentmarked member'}
 const structuredOffers=p.price_low&&p.price_high?{'@type':'AggregateOffer',priceCurrency:'USD',lowPrice:Number(p.price_low),highPrice:Number(p.price_high)}:(p.price_low||p.price_high)?{'@type':'Offer',priceCurrency:'USD',price:Number(p.price_low||p.price_high)}:undefined
 const jsonLd={'@context':'https://schema.org','@type':'Product',name:p.name,description:p.description||undefined,image:p.image_url||undefined,brand:{'@type':'Brand',name:brand},category:'Fragrance',url:'https://scentmarked.m-worley816.workers.dev/perfume/'+p.slug,offers:structuredOffers,aggregateRating:avg?{'@type':'AggregateRating',ratingValue:Number(avg),ratingCount:overallRatings.length,bestRating:5,worstRating:1}:undefined}
 return <main className="profile-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><section className="profile-hero"><div className="profile-visual"><div className="profile-art">{p.image_url?<img className="profile-product-image" src={p.image_url} alt={`${p.name} by ${brand}`} loading="eager"/>:<div className="profile-bottle catalog-placeholder"><span>{brand}</span><b>{p.name}</b><small>{p.concentration||'FRAGRANCE'}</small></div>}</div>{p.image_url&&<div className="profile-thumbnails" aria-label="Fragrance images"><span className="active"><img src={p.image_url} alt="" /></span></div>}</div><div className="profile-info"><p className="breadcrumbs"><Link href="/">Home</Link>　›　{p.brands?.slug?<Link href={'/brand/'+p.brands.slug}>{brand}</Link>:brand}　›　{p.name}</p><div className="profile-title-row"><div><p className="eyebrow">{brand}</p><h1>{p.name}</h1></div><ProfileQuickActions perfumeId={p.id} name={p.name} initialFavorite={favorite}/></div>
 {avg?<p className="rating">★ {avg} <span>{overallRatings.length} community rating{overallRatings.length===1?'':'s'}</span></p>:<p className="verified-label">COMMUNITY RATING NOT YET AVAILABLE</p>}
 {heroNotes.length>0&&<div className="profile-tags">{heroNotes.map((n:any)=><Link href={'/discover?note='+encodeURIComponent(n.name)} key={n.slug||n.name}>{n.name}</Link>)}</div>}<p className="profile-desc">{p.description||'Verified scent details are being added.'}</p><div className="profile-facts">{p.concentration&&<span><b>Concentration</b>{p.concentration}</span>}{p.release_year&&<span><b>Released</b>{p.release_year}</span>}{p.country&&<span><b>Origin</b>{p.country}</span>}{p.gender_marketing&&<span><b>Marketed for</b>{p.gender_marketing}</span>}{(p.price_low||p.price_high)&&<span><b>Price range</b>{p.price_low&&p.price_high?`${p.price_low}–${p.price_high}`:p.price_low?`From ${p.price_low}`:`Up to ${p.price_high}`}</span>}</div><div className="profile-actions"><MarkScent perfumeId={p.id} initial={initialMarks}/><Link className="button" href={'/matches?perfume='+p.slug}>Find Similar　→</Link><Link className="button ghost" href={'/compare?a='+p.slug}>Compare　⇄</Link>{featuredOffer&&<a className="button ghost" href={featuredOffer.affiliate_url} target="_blank" rel="sponsored noreferrer">Shop {featuredOffer.merchant_name}　↗</a>}</div>{featuredOffer&&<p className="muted">Shopping link may be an affiliate link. Additional approved retailers appear below.</p>}</div></section>
 <section className="profile-body"><div className="dna-side"><p className="eyebrow">SCENT PROFILE</p><h2>Scentmarked DNA</h2><p className="dna-intro">The verified scent structure that makes this fragrance unique.</p>{accords.length?[...accords].sort((a:any,b:any)=>(b.strength||0)-(a.strength||0)).slice(0,8).map((a:any)=><div className="dna-bar" key={a.accords?.name}><span>{a.accords?.name?<Link href={'/discover?accord='+encodeURIComponent(a.accords.name)}>{a.accords.name}</Link>:''}</span><i><b style={{width:(a.strength||0)+'%'}}/></i><em>{a.strength}%</em></div>):<p className="muted">Accord strength data has not been verified for this fragrance yet.</p>}<p className="muted">Select a scent family to discover other fragrances with that accord.</p></div>
 <div className="notes-side"><div className="notes-heading"><p className="eyebrow">NOTE PYRAMID</p><h2>What you’ll smell</h2></div>{[['top','Top Notes','✦'],['heart','Heart Notes','❀'],['base','Base Notes','◆'],['unspecified','Other Verified Notes','◇']].map(([pos,label,icon])=>{const list=group(pos);return list.length?<div className={"note-tier note-tier-"+pos} key={pos}><div className="note-tier-title"><span>{icon}</span><h3>{label}</h3><small>{list.length} verified</small></div><div className="note-cloud">{list.map((n:any)=><Link href={'/discover?note='+encodeURIComponent(n.name)} key={n.slug||n.name}><span className="note-symbol">{icon}</span><b>{n.name}</b></Link>)}</div></div>:null})}</div></section>
 <section className="relationship-alerts"><div className="relationship-head"><div><p className="eyebrow">SCENT RELATIONSHIPS</p><h2>Clone & similarity check</h2><p>Documented relationships that can help you avoid buying a fragrance that is too close to one you already know.</p></div></div>{relationships.length?<div className="relationship-grid">{relationships.map((r:any)=>{const type=String(r.relationship_type||'').toLowerCase(),isSource=r.source_perfume_id===p.id,label=type==='manufacturer_inspired_by'?(isSource?'Manufacturer-described inspiration':'Inspires this scent'):type==='possible_clone'?'Possible clone relationship':type==='similar_dna'?'Similar DNA':type==='flanker'?'Same fragrance family':type==='community_comparison'?'Community comparison':'Related scent',warning=type==='manufacturer_inspired_by'&&isSource?'This fragrance is described by its manufacturer as inspired by the scent below.':type==='possible_clone'?'This is a documented possible-clone relationship, not a claim that the fragrances are identical.':type==='community_comparison'?'Fragrance communities or editorial sources compare these scents. It is not a manufacturer-confirmed clone claim.':null;return <article key={r.id} className={'relationship-card '+type}><span>{label}</span><div><small>{r.related.brands?.name||'Fragrance'}</small><h3>{r.related.name}</h3>{warning&&<p><strong>{warning}</strong></p>}{r.confidence!=null&&<p>Evidence confidence: {Number(r.confidence)}%</p>}{r.evidence_source&&(evidenceUrl(r.evidence_source)?<p><a className="text-link" href={evidenceUrl(r.evidence_source)!} target="_blank" rel="noreferrer">VIEW RELATIONSHIP EVIDENCE ↗</a></p>:<p className="muted">Evidence: {r.evidence_source}</p>)}<div className="result-actions"><Link className="text-link" href={'/perfume/'+r.related.slug}>VIEW PROFILE →</Link><Link className="text-link" href={'/compare?a='+p.slug+'&b='+r.related.slug}>COMPARE BOTH →</Link></div></div></article>})}</div>:<div className="relationship-empty"><b>No documented clone relationship on file.</b><p>ScentMarked does not label a fragrance as a clone based only on shared notes.</p></div>}</section>
 <section className="community-performance"><div className="performance-head"><div><p className="eyebrow">PERFORMANCE</p><h2>How it wears</h2><p>Community-reported wear data from Scentmarked members.</p></div>{overallRatings.length>0&&<span className="performance-count">{overallRatings.length} rating{overallRatings.length===1?'':'s'}</span>}</div>{(longevity||projection||sweetness)?<div className="performance-grid">{performanceMetrics.map(({key,label,value,icon})=>value?<article className="performance-card" key={key}><span className="performance-icon">{icon}</span><div><small>{label}</small><strong>{metricLabel(key,value)}</strong><div className="performance-meter" aria-label={label+' '+value+' out of 5'}><i style={{width:(Number(value)/5*100)+'%'}}/></div><em>{value}/5 community average</em></div></article>:null)}</div>:<div className="performance-empty"><b>Be one of the first to rate how it wears.</b><p>Community performance data will appear here as members rate longevity, projection, and sweetness.</p></div>}</section>
 <section className="community-love"><div className="community-love-head"><div><p className="eyebrow">COMMUNITY LOVE</p><h2>What Scentmarked members think</h2><p>Ratings and wear experiences from the fragrance community.</p></div><div className="community-score">{avg?<><strong>{avg}</strong><span className="review-stars">{'★'.repeat(Math.round(Number(avg)))}</span><small>{overallRatings.length} rating{overallRatings.length===1?'':'s'}</small></>:<><strong>—</strong><small>Not rated yet</small></>}</div></div><div className="community-rate"><RateScent perfumeId={p.id}/></div>{ratings.some((r:any)=>r.review?.trim())?<><div className="review-section-head"><h3>Member reviews</h3><Link className="text-link" href="/community">VIEW COMMUNITY →</Link></div><div className="review-grid">{ratings.filter((r:any)=>r.review?.trim()).sort((a:any,b:any)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()).slice(0,6).map((r:any,i:number)=><article key={r.created_at+'-'+i}>{Number(r.overall)>0&&<p className="review-stars">{'★'.repeat(Math.max(1,Math.min(5,Number(r.overall))))}</p>}<p>{r.review}</p><span>— {reviewerName(r)}</span></article>)}</div></>:<div className="reviews-empty"><b>No written reviews yet.</b><p>Rate this fragrance above and share your experience with the community.</p></div>}</section>
 {featuredOffer&&<section className="source-card affiliate-offers"><div className="source-head"><div><p className="eyebrow">WHERE TO BUY</p><h2>Shop this fragrance</h2><p>Compare approved retailer options below. Some links may be affiliate links, which means ScentMarked may earn a commission at no additional cost to you. Retailer placement is separate from ScentMarked's scent-match and relationship recommendations.</p></div></div><div className="source-row featured-offer"><div><span className="source-badge primary">Featured retailer · priority {featuredOffer.priority}</span><strong>{featuredOffer.merchant_name}</strong>{featuredOffer.label&&<p>{featuredOffer.label}</p>}{featuredOffer.price!=null&&<p>{offerPrice(featuredOffer)}</p>}</div><a className="button" href={featuredOffer.affiliate_url} target="_blank" rel="sponsored noreferrer">Shop {featuredOffer.merchant_name} ↗</a></div>{additionalOffers.length>0&&<><h3>More retailers</h3><div className="source-list">{additionalOffers.map((x:any)=><div className="source-row" key={x.id}><div><strong>{x.merchant_name}</strong><small>Retailer priority {x.priority}</small>{x.label&&<p>{x.label}</p>}{x.price!=null&&<p>{offerPrice(x)}</p>}</div><a href={x.affiliate_url} target="_blank" rel="sponsored noreferrer">Shop now ↗</a></div>)}</div></>}</section>}
 <section className="source-card"><div className="source-head"><div><p className="eyebrow">VERIFICATION</p><h2>Sources & verification</h2><p>References used to support the fragrance details shown on this profile.</p></div><span className="source-count">{sources.length} source{sources.length===1?'':'s'}</span></div>{sources.length?<div className="source-list">{sources.map((x:any)=><div className="source-row" key={x.id}><div><strong><span className={x.is_primary?'source-badge primary':'source-badge'}>{x.is_primary?'Primary':'Reference'}</span>{x.source_name}</strong>{(x.fields_verified||[]).length>0?<p>Verified: {(x.fields_verified||[]).join(' · ')}</p>:<p className="muted">Verified fields not specified.</p>}</div>{x.source_url?<a href={x.source_url} target="_blank" rel="noreferrer">View source ↗</a>:<span className="muted">URL not provided</span>}</div>)}</div>:<div className="source-empty"><b>Verification details are being added.</b><p>Source provenance has not been published for this fragrance yet.</p></div>}</section></main>
}