import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

async function admin(next:string){const s=await createClient();const {data:{user}}=await s.auth.getUser();if(!user)redirect('/login?next='+encodeURIComponent(next));const {data}=await s.from('profiles').select('is_admin').eq('id',user.id).maybeSingle();if(data?.is_admin!==true)redirect('/discover');return s}
const slug=(x:string)=>x.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'')

async function save(formData:FormData){'use server';const id=String(formData.get('id')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next);const payload={name:String(formData.get('name')||'').trim(),description:String(formData.get('description')||'').trim(),concentration:String(formData.get('concentration')||'').trim(),release_year:Number(formData.get('release_year'))||null,country:String(formData.get('country')||'').trim()||null,status:String(formData.get('status')||'draft')};if(!payload.name)redirect(next+'?error='+encodeURIComponent('Fragrance name is required.'));const {error}=await s.from('perfumes').update(payload).eq('id',id);if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=1')}

async function addNote(formData:FormData){'use server';const id=String(formData.get('id')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next),name=String(formData.get('note')||'').trim(),position=String(formData.get('position')||'unspecified');if(!name)redirect(next+'?error='+encodeURIComponent('Enter a note name.'));let noteId:string|undefined;const existing=await s.from('notes').select('id').ilike('name',name).limit(1).maybeSingle();if(existing.data?.id)noteId=existing.data.id;else{const made=await s.from('notes').insert({name,slug:slug(name)}).select('id').single();if(made.error)redirect(next+'?error='+encodeURIComponent(made.error.message));noteId=made.data.id}const {error}=await s.from('perfume_notes').upsert({perfume_id:id,note_id:noteId,position},{onConflict:'perfume_id,note_id,position'});if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=note')}

async function updateNote(formData:FormData){'use server';const id=String(formData.get('id')||''),noteId=String(formData.get('note_id')||''),oldPosition=String(formData.get('old_position')||''),position=String(formData.get('position')||'unspecified'),next='/admin/perfumes/'+id+'/edit',s=await admin(next);const {error}=await s.from('perfume_notes').update({position}).eq('perfume_id',id).eq('note_id',noteId).eq('position',oldPosition);if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=note')}

async function removeNote(formData:FormData){'use server';const id=String(formData.get('id')||''),noteId=String(formData.get('note_id')||''),position=String(formData.get('position')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next);await s.from('perfume_notes').delete().eq('perfume_id',id).eq('note_id',noteId).eq('position',position);redirect(next+'?saved=note')}

async function deleteSource(formData:FormData){'use server';const id=String(formData.get('id')||''),sourceId=String(formData.get('source_id')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next);const {error}=await s.from('perfume_sources').delete().eq('id',sourceId).eq('perfume_id',id);if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=source')}

async function updateSource(formData:FormData){'use server';const id=String(formData.get('id')||''),sourceId=String(formData.get('source_id')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next),source_name=String(formData.get('source_name')||'').trim(),source_url=String(formData.get('source_url')||'').trim();if(!source_name||!source_url)redirect(next+'?error='+encodeURIComponent('Source name and URL are required.'));try{new URL(source_url)}catch{redirect(next+'?error='+encodeURIComponent('Enter a valid source URL.'))}const fields=String(formData.get('fields_verified')||'').split(',').map(x=>x.trim()).filter(Boolean);const {error}=await s.from('perfume_sources').update({source_name,source_url,source_type:String(formData.get('source_type')||'retailer_reference'),fields_verified:fields,is_primary:formData.get('is_primary')==='on',checked_at:new Date().toISOString()}).eq('id',sourceId).eq('perfume_id',id);if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=source')}

async function addSource(formData:FormData){'use server';const id=String(formData.get('id')||''),next='/admin/perfumes/'+id+'/edit',s=await admin(next),source_name=String(formData.get('source_name')||'').trim(),source_url=String(formData.get('source_url')||'').trim();if(!source_name||!source_url)redirect(next+'?error='+encodeURIComponent('Source name and URL are required.'));try{new URL(source_url)}catch{redirect(next+'?error='+encodeURIComponent('Enter a valid source URL.'))}const fields=String(formData.get('fields_verified')||'').split(',').map(x=>x.trim()).filter(Boolean);const {error}=await s.from('perfume_sources').upsert({perfume_id:id,source_name,source_url,source_type:String(formData.get('source_type')||'retailer_reference'),fields_verified:fields,is_primary:formData.get('is_primary')==='on',checked_at:new Date().toISOString()},{onConflict:'perfume_id,source_url'});if(error)redirect(next+'?error='+encodeURIComponent(error.message));redirect(next+'?saved=source')}

export default async function Edit({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string;saved?:string}>}){const {id}=await params,p=await searchParams,s=await admin('/admin/perfumes/'+id+'/edit');const {data:x,error}=await s.from('perfumes').select('id,name,slug,description,concentration,release_year,country,status,brands(name),perfume_notes(position,note_id,notes(name)),perfume_sources(id,source_name,source_url,source_type,fields_verified,is_primary,checked_at)').eq('id',id).maybeSingle();if(error||!x)redirect('/admin');const perfume:any=x,notes:any[]=perfume.perfume_notes||[],sources:any[]=perfume.perfume_sources||[];
return <main><section className="admin-editor"><p className="eyebrow">ADMIN · EDIT FRAGRANCE</p><h1 className="page-title">{perfume.name}</h1><p className="lede">{perfume.brands?.name} · Maintain the catalog record and its verification trail.</p>{p.saved&&<div className="notice">Changes saved.</div>}{p.error&&<div className="notice error">{p.error}</div>}
<div className="admin-editor-grid"><div><h2>Core record</h2><form action={save} className="form"><input type="hidden" name="id" value={perfume.id}/><label>Fragrance name<input name="name" required defaultValue={perfume.name}/></label><label>Concentration<input name="concentration" defaultValue={perfume.concentration||''}/></label><label>Release year<input name="release_year" type="number" min="1800" max="2100" defaultValue={perfume.release_year||''}/></label><label>Country<input name="country" defaultValue={perfume.country||''}/></label><label>Description<textarea name="description" rows={7} defaultValue={perfume.description||''}/></label><label>Status<select name="status" defaultValue={perfume.status||'draft'}><option value="draft">Draft</option><option value="published">Published</option></select></label><button className="button">Save Changes</button></form></div>
<div><section className="admin-panel"><h2>Verified notes</h2><div className="admin-note-list admin-note-editor">{notes.map(n=><div className="admin-note-row" key={n.note_id+'-'+n.position}><b>{n.notes?.name}</b><form action={updateNote}><input type="hidden" name="id" value={id}/><input type="hidden" name="note_id" value={n.note_id}/><input type="hidden" name="old_position" value={n.position}/><select name="position" defaultValue={n.position}><option value="top">Top</option><option value="heart">Heart</option><option value="base">Base</option><option value="unspecified">Unspecified</option></select><button>Update</button></form><form action={removeNote}><input type="hidden" name="id" value={id}/><input type="hidden" name="note_id" value={n.note_id}/><input type="hidden" name="position" value={n.position}/><button className="danger-link" aria-label={'Remove '+n.notes?.name}>Remove</button></form></div>)}</div><form action={addNote} className="mini-form"><input type="hidden" name="id" value={id}/><input name="note" placeholder="Note name" required/><select name="position" defaultValue="unspecified"><option value="top">Top</option><option value="heart">Heart</option><option value="base">Base</option><option value="unspecified">Unspecified</option></select><button className="button">Add Note</button></form></section>
<section className="admin-panel"><h2>Source verification</h2>{sources.map(x=><details className="admin-source" key={x.id}><summary><strong>{x.is_primary?'✓ ':''}{x.source_name}</strong><span>Manage</span></summary><a href={x.source_url} target="_blank" rel="noreferrer">Open source ↗</a><form action={updateSource} className="form compact"><input type="hidden" name="id" value={id}/><input type="hidden" name="source_id" value={x.id}/><label>Source name<input name="source_name" required defaultValue={x.source_name}/></label><label>Source URL<input name="source_url" type="url" required defaultValue={x.source_url}/></label><label>Source type<select name="source_type" defaultValue={x.source_type}><option value="official">Official manufacturer</option><option value="retailer_reference">Retailer reference</option><option value="editorial_reference">Editorial reference</option></select></label><label>Fields verified<input name="fields_verified" defaultValue={(x.fields_verified||[]).join(', ')}/></label><label className="check-row"><input type="checkbox" name="is_primary" defaultChecked={x.is_primary}/> Primary source</label><button className="button">Update Source</button></form><form action={deleteSource}><input type="hidden" name="id" value={id}/><input type="hidden" name="source_id" value={x.id}/><button className="danger-link">Delete source</button></form></details>)}<form action={addSource} className="form compact"><input type="hidden" name="id" value={id}/><label>Source name<input name="source_name" placeholder="Official brand or retailer" required/></label><label>Source URL<input name="source_url" type="url" placeholder="https://…" required/></label><label>Source type<select name="source_type" defaultValue="official"><option value="official">Official manufacturer</option><option value="retailer_reference">Retailer reference</option><option value="editorial_reference">Editorial reference</option></select></label><label>Fields verified<input name="fields_verified" placeholder="notes, year, concentration"/></label><label className="check-row"><input type="checkbox" name="is_primary"/> Primary source</label><button className="button">Save Source</button></form></section></div></div></section></main>}
