create table if not exists public.sponsorship_events (
 id bigint generated by default as identity primary key,
 campaign_id bigint not null references public.sponsorship_campaigns(id) on delete cascade,
 event_type text not null check (event_type in ('impression','click')),
 placement text not null,
 occurred_at timestamptz not null default now(),
 metadata jsonb not null default '{}'::jsonb
);
alter table public.sponsorship_events enable row level security;
revoke all on public.sponsorship_events from anon, authenticated;
grant all on public.sponsorship_events to service_role;
create index if not exists sponsorship_events_campaign_idx on public.sponsorship_events(campaign_id,event_type,occurred_at desc);
