create table if not exists public.membership_plans (
 id bigint generated by default as identity primary key,
 slug text not null unique,
 name text not null,
 description text,
 price_cents bigint not null default 0 check (price_cents >= 0),
 billing_interval text not null default 'month' check (billing_interval in ('month','year','one_time')),
 currency text not null default 'USD' check (char_length(currency)=3),
 entitlements jsonb not null default '[]'::jsonb,
 is_active boolean not null default true,
 sort_order integer not null default 0,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.membership_plans enable row level security;
revoke all on public.membership_plans from anon, authenticated;
grant all on public.membership_plans to service_role;

create table if not exists public.member_subscriptions (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 plan_id bigint not null references public.membership_plans(id),
 provider text,
 provider_customer_id text,
 provider_subscription_id text,
 status text not null default 'inactive' check (status in ('inactive','trialing','active','past_due','cancelled','expired')),
 current_period_start timestamptz,
 current_period_end timestamptz,
 cancel_at_period_end boolean not null default false,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(provider,provider_subscription_id)
);
alter table public.member_subscriptions enable row level security;
revoke all on public.member_subscriptions from anon, authenticated;
grant all on public.member_subscriptions to service_role;
create index if not exists member_subscriptions_user_idx on public.member_subscriptions(user_id,status,current_period_end desc);

insert into public.membership_plans(slug,name,description,price_cents,billing_interval,currency,entitlements,sort_order)
values
 ('free','Free','Core ScentMarked discovery and community features.',0,'month','USD','["catalog","compare","community","basic_matches"]'::jsonb,0),
 ('plus','ScentMarked Plus','Premium personalization and collection tools.',699,'month','USD','["catalog","compare","community","basic_matches","advanced_matches","taste_insights","unlimited_lists","deal_alerts"]'::jsonb,10)
on conflict(slug) do nothing;
