-- ScentMarked CRM + email foundation
-- New product functionality. This is intentionally separate from the reconstructed production baseline.

create table if not exists public.crm_contacts (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  email text not null,
  first_name text,
  last_name text,
  status text not null default 'active' check (status in ('active','unsubscribed','bounced','suppressed')),
  source text not null default 'scentmarked',
  marketing_consent boolean not null default false,
  marketing_consented_at timestamptz,
  unsubscribed_at timestamptz,
  last_engaged_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint crm_contacts_email_length check (char_length(email) between 3 and 254)
);

create unique index if not exists crm_contacts_email_lower_key
  on public.crm_contacts (lower(email));
create index if not exists crm_contacts_user_id_idx on public.crm_contacts(user_id);
create index if not exists crm_contacts_status_idx on public.crm_contacts(status);
create index if not exists crm_contacts_created_at_idx on public.crm_contacts(created_at desc);

create table if not exists public.crm_tags (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.crm_contact_tags (
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  tag_id bigint not null references public.crm_tags(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (contact_id, tag_id)
);
create index if not exists crm_contact_tags_tag_id_idx on public.crm_contact_tags(tag_id);

create table if not exists public.crm_notes (
  id bigint generated by default as identity primary key,
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  author_user_id uuid references auth.users(id) on delete set null,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);
create index if not exists crm_notes_contact_created_idx
  on public.crm_notes(contact_id, created_at desc);

create table if not exists public.crm_segments (
  id bigint generated by default as identity primary key,
  name text not null unique,
  description text,
  rules jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_templates (
  id bigint generated by default as identity primary key,
  name text not null unique,
  subject text not null,
  preview_text text,
  html_body text not null,
  text_body text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  template_id bigint references public.email_templates(id) on delete set null,
  segment_id bigint references public.crm_segments(id) on delete set null,
  subject text not null,
  preview_text text,
  html_body text not null,
  text_body text,
  status text not null default 'draft'
    check (status in ('draft','scheduled','sending','sent','cancelled','failed')),
  scheduled_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists email_campaigns_status_idx on public.email_campaigns(status);
create index if not exists email_campaigns_scheduled_at_idx on public.email_campaigns(scheduled_at);

create table if not exists public.email_deliveries (
  id bigint generated by default as identity primary key,
  campaign_id uuid references public.email_campaigns(id) on delete cascade,
  contact_id uuid not null references public.crm_contacts(id) on delete cascade,
  provider_message_id text,
  status text not null default 'queued'
    check (status in ('queued','sent','delivered','opened','clicked','bounced','complained','failed','unsubscribed')),
  sent_at timestamptz,
  delivered_at timestamptz,
  opened_at timestamptz,
  clicked_at timestamptz,
  bounced_at timestamptz,
  failed_at timestamptz,
  error_message text,
  created_at timestamptz not null default now(),
  unique (campaign_id, contact_id)
);
create index if not exists email_deliveries_contact_idx on public.email_deliveries(contact_id);
create index if not exists email_deliveries_status_idx on public.email_deliveries(status);
create index if not exists email_deliveries_provider_message_idx on public.email_deliveries(provider_message_id);

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  delivery_id bigint references public.email_deliveries(id) on delete cascade,
  contact_id uuid references public.crm_contacts(id) on delete cascade,
  event_type text not null
    check (event_type in ('sent','delivered','opened','clicked','bounced','complained','failed','unsubscribed')),
  provider_event_id text,
  metadata jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
create unique index if not exists email_events_provider_event_key
  on public.email_events(provider_event_id)
  where provider_event_id is not null;
create index if not exists email_events_delivery_idx on public.email_events(delivery_id);
create index if not exists email_events_contact_idx on public.email_events(contact_id);
create index if not exists email_events_occurred_at_idx on public.email_events(occurred_at desc);

-- CRM and campaign management are admin-only. Service-role operations bypass RLS
-- for trusted provider/webhook processing.
alter table public.crm_contacts enable row level security;
alter table public.crm_tags enable row level security;
alter table public.crm_contact_tags enable row level security;
alter table public.crm_notes enable row level security;
alter table public.crm_segments enable row level security;
alter table public.email_templates enable row level security;
alter table public.email_campaigns enable row level security;
alter table public.email_deliveries enable row level security;
alter table public.email_events enable row level security;

create policy "admins_manage_crm_contacts" on public.crm_contacts
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_crm_tags" on public.crm_tags
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_crm_contact_tags" on public.crm_contact_tags
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_crm_notes" on public.crm_notes
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_crm_segments" on public.crm_segments
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_email_templates" on public.email_templates
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_manage_email_campaigns" on public.email_campaigns
for all to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true))
with check (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_read_email_deliveries" on public.email_deliveries
for select to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));

create policy "admins_read_email_events" on public.email_events
for select to authenticated
using (exists (select 1 from public.profiles p where p.id = (select auth.uid()) and p.is_admin = true));
