-- ScentMarked CRM + email production migration.
-- Consolidated from the 20261003 CRM/email development migrations.
-- Requires the existing profiles scent questionnaire columns and profiles.is_admin.

create table public.crm_contacts (
 id uuid primary key default gen_random_uuid(), user_id uuid unique references auth.users(id) on delete set null,
 email text not null, first_name text, last_name text,
 status text not null default 'active' check(status in('active','unsubscribed','bounced','suppressed')),
 source text not null default 'scentmarked', marketing_consent boolean not null default false,
 marketing_consented_at timestamptz, unsubscribed_at timestamptz, last_engaged_at timestamptz,
 unsubscribe_token uuid not null default gen_random_uuid(),
 created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
 constraint crm_contacts_email_length check(char_length(email) between 3 and 254)
);
create unique index crm_contacts_email_lower_key on public.crm_contacts(lower(email));
create unique index crm_contacts_unsubscribe_token_key on public.crm_contacts(unsubscribe_token);
create index crm_contacts_user_id_idx on public.crm_contacts(user_id);
create index crm_contacts_status_idx on public.crm_contacts(status);
create index crm_contacts_created_at_idx on public.crm_contacts(created_at desc);

create table public.crm_tags(id bigint generated by default as identity primary key,name text not null unique,description text,created_at timestamptz not null default now());
create table public.crm_contact_tags(contact_id uuid not null references public.crm_contacts(id) on delete cascade,tag_id bigint not null references public.crm_tags(id) on delete cascade,created_at timestamptz not null default now(),primary key(contact_id,tag_id));
create index crm_contact_tags_tag_id_idx on public.crm_contact_tags(tag_id);
create table public.crm_notes(id bigint generated by default as identity primary key,contact_id uuid not null references public.crm_contacts(id) on delete cascade,author_user_id uuid references auth.users(id) on delete set null,body text not null check(char_length(body) between 1 and 4000),created_at timestamptz not null default now());
create index crm_notes_contact_created_idx on public.crm_notes(contact_id,created_at desc);
create table public.crm_segments(id bigint generated by default as identity primary key,name text not null unique,description text,rules jsonb not null default '{}'::jsonb,is_active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.email_templates(id bigint generated by default as identity primary key,name text not null unique,subject text not null,preview_text text,html_body text not null,text_body text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.email_campaigns(id uuid primary key default gen_random_uuid(),name text not null,template_id bigint references public.email_templates(id) on delete set null,segment_id bigint references public.crm_segments(id) on delete set null,subject text not null,preview_text text,html_body text not null,text_body text,status text not null default 'draft' check(status in('draft','scheduled','sending','sent','cancelled','failed')),scheduled_at timestamptz,started_at timestamptz,completed_at timestamptz,created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index email_campaigns_status_idx on public.email_campaigns(status);
create index email_campaigns_scheduled_at_idx on public.email_campaigns(scheduled_at);
create table public.email_deliveries(id bigint generated by default as identity primary key,campaign_id uuid references public.email_campaigns(id) on delete cascade,contact_id uuid not null references public.crm_contacts(id) on delete cascade,provider_message_id text,status text not null default 'queued' check(status in('queued','sent','delivered','opened','clicked','bounced','complained','failed','unsubscribed','skipped')),sent_at timestamptz,delivered_at timestamptz,opened_at timestamptz,clicked_at timestamptz,bounced_at timestamptz,failed_at timestamptz,skipped_at timestamptz,error_message text,created_at timestamptz not null default now(),unique(campaign_id,contact_id));
create index email_deliveries_contact_idx on public.email_deliveries(contact_id);
create index email_deliveries_status_idx on public.email_deliveries(status);
create index email_deliveries_provider_message_idx on public.email_deliveries(provider_message_id);
create table public.email_events(id bigint generated by default as identity primary key,delivery_id bigint references public.email_deliveries(id) on delete cascade,contact_id uuid references public.crm_contacts(id) on delete cascade,event_type text not null check(event_type in('sent','delivered','opened','clicked','bounced','complained','failed','unsubscribed')),provider_event_id text,metadata jsonb not null default '{}'::jsonb,occurred_at timestamptz not null default now(),created_at timestamptz not null default now());
create unique index email_events_provider_event_key on public.email_events(provider_event_id) where provider_event_id is not null;
create index email_events_delivery_idx on public.email_events(delivery_id);
create index email_events_contact_idx on public.email_events(contact_id);
create index email_events_occurred_at_idx on public.email_events(occurred_at desc);

alter table public.crm_contacts enable row level security; alter table public.crm_tags enable row level security; alter table public.crm_contact_tags enable row level security; alter table public.crm_notes enable row level security; alter table public.crm_segments enable row level security; alter table public.email_templates enable row level security; alter table public.email_campaigns enable row level security; alter table public.email_deliveries enable row level security; alter table public.email_events enable row level security;

create policy admins_manage_crm_contacts on public.crm_contacts for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_crm_tags on public.crm_tags for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_crm_contact_tags on public.crm_contact_tags for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_crm_notes on public.crm_notes for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_crm_segments on public.crm_segments for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_email_templates on public.email_templates for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_email_campaigns on public.email_campaigns for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_manage_email_deliveries on public.email_deliveries for all to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true)) with check(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));
create policy admins_read_email_events on public.email_events for select to authenticated using(exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.is_admin=true));

create view public.crm_emailable_contacts with(security_invoker=true) as select c.* from public.crm_contacts c where c.status='active' and c.marketing_consent=true and c.marketing_consented_at is not null and c.unsubscribed_at is null;

create or replace function public.normalize_crm_contact_consent() returns trigger language plpgsql set search_path=public as $$ begin
 if new.marketing_consent=true and old.marketing_consent is distinct from true then new.marketing_consented_at:=coalesce(new.marketing_consented_at,now());new.unsubscribed_at:=null;if new.status='unsubscribed' then new.status:='active';end if;
 elsif new.marketing_consent=false and old.marketing_consent=true then new.marketing_consented_at:=null;new.unsubscribed_at:=coalesce(new.unsubscribed_at,now());if new.status='active' then new.status:='unsubscribed';end if; end if;
 if new.status='unsubscribed' then new.marketing_consent:=false;new.marketing_consented_at:=null;new.unsubscribed_at:=coalesce(new.unsubscribed_at,now());end if; new.updated_at:=now();return new; end $$;
create trigger normalize_crm_contact_consent_before_update before update of marketing_consent,status on public.crm_contacts for each row execute function public.normalize_crm_contact_consent();

create or replace function public.enforce_email_delivery_consent() returns trigger language plpgsql set search_path=public as $$ begin if new.status='queued' and not exists(select 1 from public.crm_emailable_contacts c where c.id=new.contact_id) then raise exception 'Contact is not eligible for marketing email delivery';end if;return new;end $$;
create trigger enforce_email_delivery_consent_before_write before insert or update of contact_id,status on public.email_deliveries for each row execute function public.enforce_email_delivery_consent();

create or replace function public.email_profile_matches_rules(p public.profiles,p_rules jsonb,p_modes jsonb default '{}'::jsonb) returns boolean language plpgsql immutable as $$
declare k text;wanted text[];actual text[];mode text;
begin foreach k in array array['loved_note','avoided_note','vibe','occasion','presentation'] loop if p_rules?k then wanted:=case when jsonb_typeof(p_rules->k)='array' then array(select jsonb_array_elements_text(p_rules->k)) else array[p_rules->>k] end; actual:=case k when 'loved_note' then coalesce(p.scent_loved_notes,'{}') when 'avoided_note' then coalesce(p.scent_avoided_notes,'{}') when 'vibe' then coalesce(p.scent_vibes,'{}') when 'occasion' then coalesce(p.scent_occasions,'{}') when 'presentation' then coalesce(p.scent_presentations,'{}') end;mode:=coalesce(p_modes->>k,'all');if mode='any' then if not(actual&&wanted) then return false;end if;else if not(actual@>wanted) then return false;end if;end if;end if;end loop;
if p_rules?'sweetness_min' and coalesce(p.scent_sweetness,0)<(p_rules->>'sweetness_min')::numeric then return false;end if;if p_rules?'projection_min' and coalesce(p.scent_projection,0)<(p_rules->>'projection_min')::numeric then return false;end if;if p_rules?'longevity_min' and coalesce(p.scent_longevity,0)<(p_rules->>'longevity_min')::numeric then return false;end if;if p_rules?'max_price' and(p.scent_max_price is null or p.scent_max_price>(p_rules->>'max_price')::numeric) then return false;end if;return true;end $$;

create or replace function public.get_email_campaign_audience(p_campaign_id uuid) returns table(contact_id uuid,email text,first_name text,unsubscribe_token uuid) language plpgsql security invoker stable set search_path=public as $$
declare v_segment_id bigint;v_rules jsonb;v_profile jsonb;v_modes jsonb;begin select segment_id into v_segment_id from public.email_campaigns where id=p_campaign_id;if not found then raise exception 'Campaign not found';end if;if v_segment_id is null then return query select c.id,c.email,c.first_name,c.unsubscribe_token from public.crm_emailable_contacts c order by c.created_at;return;end if;select rules into v_rules from public.crm_segments where id=v_segment_id and is_active=true;if v_rules is null then raise exception 'Campaign segment is unavailable';end if;v_profile:=coalesce(v_rules->'profile','{}');v_modes:=coalesce(v_rules->'match_modes','{}');return query select c.id,c.email,c.first_name,c.unsubscribe_token from public.crm_emailable_contacts c left join public.profiles p on p.id=c.user_id where v_profile='{}' or(p.id is not null and public.email_profile_matches_rules(p,v_profile,v_modes)) order by c.created_at;end $$;

create or replace function public.count_email_segment_audience(p_segment_id bigint) returns integer language plpgsql security invoker stable set search_path=public as $$ declare v_rules jsonb;v_profile jsonb;v_modes jsonb;v_count integer;begin select rules into v_rules from public.crm_segments where id=p_segment_id and is_active=true;if v_rules is null then return 0;end if;v_profile:=coalesce(v_rules->'profile','{}');v_modes:=coalesce(v_rules->'match_modes','{}');select count(*)::integer into v_count from public.crm_emailable_contacts c left join public.profiles p on p.id=c.user_id where v_profile='{}' or(p.id is not null and public.email_profile_matches_rules(p,v_profile,v_modes));return v_count;end $$;

create or replace function public.preview_email_segment_audience(p_segment_id bigint,p_limit integer default 25) returns table(contact_id uuid,email text,first_name text,last_name text) language plpgsql security invoker stable set search_path=public as $$ declare v_rules jsonb;v_profile jsonb;v_modes jsonb;v_limit integer;begin select rules into v_rules from public.crm_segments where id=p_segment_id and is_active=true;if v_rules is null then return;end if;v_profile:=coalesce(v_rules->'profile','{}');v_modes:=coalesce(v_rules->'match_modes','{}');v_limit:=greatest(1,least(coalesce(p_limit,25),50));return query select c.id,c.email,c.first_name,c.last_name from public.crm_emailable_contacts c left join public.profiles p on p.id=c.user_id where v_profile='{}' or(p.id is not null and public.email_profile_matches_rules(p,v_profile,v_modes)) order by c.created_at desc limit v_limit;end $$;

create or replace function public.queue_email_campaign(p_campaign_id uuid) returns integer language plpgsql security invoker set search_path=public as $$ declare n integer;begin if not exists(select 1 from public.email_campaigns where id=p_campaign_id and status='draft') then raise exception 'Campaign must be a draft';end if;insert into public.email_deliveries(campaign_id,contact_id,status) select p_campaign_id,contact_id,'queued' from public.get_email_campaign_audience(p_campaign_id) on conflict(campaign_id,contact_id) do nothing;get diagnostics n=row_count;return n;end $$;

create or replace function public.start_email_campaign(p_campaign_id uuid) returns void language plpgsql security invoker set search_path=public as $$ begin update public.email_campaigns set status='sending',started_at=coalesce(started_at,now()),updated_at=now() where id=p_campaign_id and(status='draft' or(status='scheduled' and scheduled_at is not null and scheduled_at<=now()));if not found then raise exception 'Campaign is not ready or its scheduled send time has not arrived';end if;end $$;
create or replace function public.finish_email_campaign(p_campaign_id uuid,p_has_failures boolean) returns void language plpgsql security invoker set search_path=public as $$ begin update public.email_campaigns set status=case when p_has_failures then 'failed' else 'sent' end,completed_at=now(),updated_at=now() where id=p_campaign_id and status='sending';if not found then raise exception 'Campaign is not currently sending';end if;end $$;
create or replace function public.schedule_email_campaign(p_campaign_id uuid,p_scheduled_at timestamptz) returns void language plpgsql security invoker set search_path=public as $$ begin if p_scheduled_at<=now() then raise exception 'Scheduled time must be in the future';end if;if not exists(select 1 from public.email_deliveries where campaign_id=p_campaign_id and status='queued') then raise exception 'Prepare the campaign audience before scheduling';end if;update public.email_campaigns set status='scheduled',scheduled_at=p_scheduled_at,updated_at=now() where id=p_campaign_id and status='draft';if not found then raise exception 'Only draft campaigns can be scheduled';end if;end $$;
create or replace function public.cancel_scheduled_email_campaign(p_campaign_id uuid) returns void language plpgsql security invoker set search_path=public as $$ begin update public.email_campaigns set status='draft',scheduled_at=null,updated_at=now() where id=p_campaign_id and status='scheduled';if not found then raise exception 'Campaign is not scheduled';end if;end $$;
create or replace function public.get_due_email_campaigns(p_limit integer default 10) returns table(campaign_id uuid) language sql security invoker stable set search_path=public as $$ select id from public.email_campaigns where status='scheduled' and scheduled_at is not null and scheduled_at<=now() order by scheduled_at limit greatest(1,least(coalesce(p_limit,10),50)) $$;
create or replace function public.retry_failed_email_deliveries(p_campaign_id uuid) returns integer language plpgsql security invoker set search_path=public as $$ declare n integer;begin update public.email_deliveries d set status='queued',failed_at=null,error_message=null,provider_message_id=null where d.campaign_id=p_campaign_id and d.status='failed' and exists(select 1 from public.crm_emailable_contacts c where c.id=d.contact_id);get diagnostics n=row_count;if n>0 then update public.email_campaigns set status='draft',completed_at=null,updated_at=now() where id=p_campaign_id and status='failed';end if;return n;end $$;
create or replace function public.delete_unused_crm_segment(p_segment_id bigint) returns boolean language plpgsql security invoker set search_path=public as $$ begin if exists(select 1 from public.email_campaigns where segment_id=p_segment_id) then raise exception 'Segment is used by an email campaign and cannot be deleted';end if;delete from public.crm_segments where id=p_segment_id;return found;end $$;

create or replace function public.unsubscribe_crm_contact(p_token uuid) returns boolean language plpgsql security definer set search_path=public as $$ declare changed boolean;begin update public.crm_contacts set marketing_consent=false,marketing_consented_at=null,status='unsubscribed',unsubscribed_at=coalesce(unsubscribed_at,now()),updated_at=now() where unsubscribe_token=p_token and(marketing_consent=true or status<>'unsubscribed');changed:=found;if not changed then return exists(select 1 from public.crm_contacts where unsubscribe_token=p_token);end if;return true;end $$;

-- Member sync is privileged because the trigger runs from auth.users. It is not directly callable.
create or replace function public.sync_member_to_crm_contact() returns trigger language plpgsql security definer set search_path=public as $$ declare member_email text;member_name text;existing_contact_id uuid;begin member_email:=nullif(trim(new.email),'');if member_email is null then return new;end if;member_name:=nullif(trim(coalesce(new.raw_user_meta_data->>'display_name','')),'');select id into existing_contact_id from public.crm_contacts where user_id=new.id or lower(email)=lower(member_email) order by case when user_id=new.id then 0 else 1 end limit 1;if existing_contact_id is not null then update public.crm_contacts set user_id=new.id,email=member_email,first_name=coalesce(first_name,member_name),updated_at=now() where id=existing_contact_id;else insert into public.crm_contacts(user_id,email,first_name,source,status,marketing_consent) values(new.id,member_email,member_name,'scentmarked_member','active',false);end if;return new;end $$;
create trigger sync_member_to_crm_contact_on_auth_user after insert or update of email,raw_user_meta_data on auth.users for each row execute function public.sync_member_to_crm_contact();

insert into public.crm_contacts(user_id,email,first_name,source,status,marketing_consent) select u.id,u.email,nullif(trim(coalesce(u.raw_user_meta_data->>'display_name','')),''),'scentmarked_member','active',false from auth.users u where u.email is not null and not exists(select 1 from public.crm_contacts c where c.user_id=u.id or lower(c.email)=lower(u.email)) on conflict do nothing;
update public.crm_contacts c set user_id=u.id,updated_at=now() from auth.users u where c.user_id is null and u.email is not null and lower(c.email)=lower(u.email);

revoke all on function public.unsubscribe_crm_contact(uuid) from public;
grant execute on function public.unsubscribe_crm_contact(uuid) to anon,authenticated;
revoke all on function public.sync_member_to_crm_contact() from public;
revoke all on function public.email_profile_matches_rules(public.profiles,jsonb,jsonb) from public;
revoke all on function public.get_email_campaign_audience(uuid) from public;
revoke all on function public.count_email_segment_audience(bigint) from public;
revoke all on function public.preview_email_segment_audience(bigint,integer) from public;
revoke all on function public.queue_email_campaign(uuid) from public;
revoke all on function public.start_email_campaign(uuid) from public;
revoke all on function public.finish_email_campaign(uuid,boolean) from public;
revoke all on function public.schedule_email_campaign(uuid,timestamptz) from public;
revoke all on function public.cancel_scheduled_email_campaign(uuid) from public;
revoke all on function public.get_due_email_campaigns(integer) from public;
revoke all on function public.retry_failed_email_deliveries(uuid) from public;
revoke all on function public.delete_unused_crm_segment(bigint) from public;
grant execute on function public.email_profile_matches_rules(public.profiles,jsonb,jsonb) to authenticated;
grant execute on function public.get_email_campaign_audience(uuid) to authenticated;
grant execute on function public.count_email_segment_audience(bigint) to authenticated;
grant execute on function public.preview_email_segment_audience(bigint,integer) to authenticated;
grant execute on function public.queue_email_campaign(uuid) to authenticated;
grant execute on function public.start_email_campaign(uuid) to authenticated;
grant execute on function public.finish_email_campaign(uuid,boolean) to authenticated;
grant execute on function public.schedule_email_campaign(uuid,timestamptz) to authenticated;
grant execute on function public.cancel_scheduled_email_campaign(uuid) to authenticated;
grant execute on function public.get_due_email_campaigns(integer) to authenticated;
grant execute on function public.retry_failed_email_deliveries(uuid) to authenticated;
grant execute on function public.delete_unused_crm_segment(bigint) to authenticated;
