create table if not exists public.affiliate_attribution_audit (
 id bigint generated by default as identity primary key,
 transaction_id bigint not null references public.monetization_transactions(id) on delete cascade,
 changed_by uuid references auth.users(id) on delete set null,
 change_source text not null check (change_source in ('manual','automatic')),
 before_values jsonb not null default '{}'::jsonb,
 after_values jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now()
);

alter table public.affiliate_attribution_audit enable row level security;

revoke all on table public.affiliate_attribution_audit from anon, authenticated;
revoke all on sequence public.affiliate_attribution_audit_id_seq from anon, authenticated;
grant select, insert on table public.affiliate_attribution_audit to service_role;
grant usage, select on sequence public.affiliate_attribution_audit_id_seq to service_role;

create index if not exists affiliate_attribution_audit_transaction_idx on public.affiliate_attribution_audit(transaction_id,created_at desc);
create index if not exists affiliate_attribution_audit_created_idx on public.affiliate_attribution_audit(created_at desc);

create index if not exists affiliate_attribution_audit_changed_by_idx on public.affiliate_attribution_audit(changed_by);
