create table if not exists public.monetization_transactions (
 id bigint generated by default as identity primary key,
 revenue_type text not null check (revenue_type in ('affiliate','sponsorship','advertising','subscription','other')),
 source_name text not null,
 external_id text,
 perfume_id uuid references public.perfumes(id) on delete set null,
 gross_cents bigint not null default 0 check (gross_cents >= 0),
 fee_cents bigint not null default 0 check (fee_cents >= 0),
 currency text not null default 'USD' check (char_length(currency)=3),
 status text not null default 'pending' check (status in ('pending','confirmed','paid','refunded','void')),
 occurred_at timestamptz not null default now(),
 paid_at timestamptz,
 notes text,
 metadata jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now(),
 unique(source_name,external_id)
);
alter table public.monetization_transactions enable row level security;
revoke all on public.monetization_transactions from anon, authenticated;
grant all on public.monetization_transactions to service_role;

create table if not exists public.sponsorship_campaigns (
 id bigint generated by default as identity primary key,
 name text not null,
 sponsor_name text not null,
 placement text not null,
 destination_url text,
 starts_at timestamptz,
 ends_at timestamptz,
 budget_cents bigint check (budget_cents is null or budget_cents >= 0),
 currency text not null default 'USD' check (char_length(currency)=3),
 status text not null default 'draft' check (status in ('draft','scheduled','active','paused','completed','cancelled')),
 disclosure_label text not null default 'Sponsored',
 notes text,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.sponsorship_campaigns enable row level security;
revoke all on public.sponsorship_campaigns from anon, authenticated;
grant all on public.sponsorship_campaigns to service_role;

create index if not exists monetization_transactions_occurred_idx on public.monetization_transactions(occurred_at desc);
create index if not exists monetization_transactions_type_idx on public.monetization_transactions(revenue_type,status);
create index if not exists sponsorship_campaigns_status_idx on public.sponsorship_campaigns(status,starts_at,ends_at);
