create table if not exists public.monetization_expenses (
 id bigint generated by default as identity primary key,
 category text not null check (category in ('hosting','software','marketing','contractor','legal','accounting','content','other')),
 vendor text,
 description text,
 amount_cents bigint not null check (amount_cents >= 0),
 currency text not null default 'USD',
 incurred_at date not null default current_date,
 created_at timestamptz not null default now()
);
alter table public.monetization_expenses enable row level security;
revoke all on table public.monetization_expenses from anon, authenticated;
revoke all on sequence public.monetization_expenses_id_seq from anon, authenticated;
grant select, insert, update, delete on table public.monetization_expenses to service_role;
grant usage, select on sequence public.monetization_expenses_id_seq to service_role;
create index if not exists monetization_expenses_incurred_idx on public.monetization_expenses(incurred_at desc);
create index if not exists monetization_expenses_category_idx on public.monetization_expenses(category);
